arcamens/urls.py
from django.urls import path, include
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
    path(r'admin/', admin.site.urls),
     path(r'core_app/', include('core_app.urls')),
     path(r'group_app/', include('group_app.urls')),
     path(r'board_app/', include('board_app.urls')),
     path(r'feedback_app/', include('feedback_app.urls')),
     path(r'site_app/', include('site_app.urls')),
     path(r'cash_app/', include('cash_app.urls')),

     path(r'post_app/', include('post_app.urls', namespace='post_app')),
     path(r'paybills/', include('paybills.urls')),
     path(r'onesignal/', include('onesignal.urls')),
    path(r'card_app/', include('card_app.urls')),
    path(r'comment_app/', include('comment_app.urls')),
    path(r'note_app/', include('note_app.urls')),
    path(r'jscroll/', include('jscroll.urls')),

    path(r'bitbucket_app/', include('bitbucket_app.urls')),
    path(r'github_app/', include('github_app.urls')),

    path(r'list_app/', include('list_app.urls')),

    path(r'', RedirectView.as_view(pattern_name='site_app:index')),
]


# handler500 = 'core_app.views.default_error'

core_app/urls.py
from django.views.generic.base import RedirectView
from django.conf.urls import re_path
from . import views

app_name = 'core_app'
urlpatterns = [
    re_path('index/', views.Index.as_view(), name='index'),
    re_path('set-timezone/', views.SetTimezone.as_view(), name='set-timezone'),
    re_path('disabled-account/(?P<user_id>.+)/', views.DisabledAccount.as_view(), name='disabled-account'),
    re_path('switch-organization/(?P<organization_id>.+)/', views.SwitchOrganization.as_view(), name='switch-organization'),
    re_path('update-user-information/', views.UpdateUserInformation.as_view(), name='update-user-information'),
    re_path('create-organization/', views.CreateOrganization.as_view(), name='create-organization'),
    re_path('select-organization/', views.SelectOrganization.as_view(), name='select-organization'),
    re_path('no-organization/', views.NoOrganization.as_view(), name='no-organization'),
    re_path('no-default/', views.NoDefault.as_view(), name='no-default'),

    re_path('seen-event/(?P<event_id>.+)/', views.SeenEvent.as_view(), name='seen-event'),
    re_path('setup-node-filter/', views.SetupNodeFilter.as_view(), name='setup-node-filter'),
    re_path('join-organization/(?P<organization_id>.+)/(?P<token>.+)/', views.JoinOrganization.as_view(), name='join-organization'),
    re_path('signup-from-invite/(?P<organization_id>.+)/(?P<token>.+)/', views.SignupFromInvite.as_view(), name='signup-from-invite'),
    re_path('update-organization/', views.UpdateOrganization.as_view(), name='update-organization'),
    re_path('delete-organization/', views.DeleteOrganization.as_view(), name='delete-organization'),
    re_path('list-users/', views.ListUsers.as_view(), name='list-users'),
    re_path('list-events/', views.ListEvents.as_view(), name='list-events'),
    re_path('shout/', views.Shout.as_view(), name='shout'),
    re_path('list-logs/', views.ListLogs.as_view(), name='list-logs'),
    re_path('all-seen/', views.AllSeen.as_view(), name='all-seen'),

    re_path('list-tags/', views.ListTags.as_view(), name='list-tags'),
    re_path('create-tag/', views.CreateTag.as_view(), name='create-tag'),
    re_path('delete-tag/(?P<tag_id>.+)/', views.DeleteTag.as_view(), name='delete-tag'),
    re_path('invite-organization-user/', views.InviteOrganizationUser.as_view(), name='invite-organization-user'),
    re_path('list-clipboard/', views.ListClipboard.as_view(), name='list-clipboard'),
    re_path('delete-all-clipboard/', views.DeleteAllClipboard.as_view(), name='delete-all-clipboard'),
    re_path('confirm-clipboard-deletion/', views.ConfirmClipboardDeletion.as_view(), name='confirm-clipboard-deletion'),
    re_path('update-password/', views.UpdatePassword.as_view(), name='update-password'),
    re_path('set-membership/(?P<organization_id>.+)/(?P<user_id>.+)/', views.SetMembership.as_view(), name='set-membership'),

    re_path('disabled-account/', views.DisabledAccount.as_view(), name='disabled-account'),
    re_path('remove-organization-user/(?P<user_id>.+)', views.RemoveOrganizationUser.as_view(), name='remove-organization-user'),
    re_path('cancel-invite/(?P<invite_id>.+)', views.CancelInvite.as_view(), name='cancel-invite'),
    re_path('list-invites/', views.ListInvites.as_view(), name='list-invites'),
    re_path('resend-invite/(?P<invite_id>.+)', views.ResendInvite.as_view(), name='resend-invite'),
    re_path('list-nodes/', views.ListNodes.as_view(), name='list-nodes'),
    re_path('list-public-organizations/', views.ListPublicOrganizations.as_view(), name='list-public-organizations'),
    re_path('resend-email-confirmation/', views.ResendEmailConfirmation.as_view(), name='resend-email-confirmation'),
    re_path('join-public-organization/(?P<organization_id>.+)/', views.JoinPublicOrganization.as_view(), name='join-public-organization'),
    re_path('not-public-organization/(?P<organization_id>.+)/', views.NotPublicOrganization.as_view(), name='not-public-organization'),
    re_path('join-from-link/(?P<organization_id>.+)/', views.JoinFromLink.as_view(), name='join-from-link'),

    re_path('unbind-user-tags/(?P<user_id>.+)/', views.UnbindUserTags.as_view(), name='unbind-user-tags'),
    re_path('bind-user-tags/(?P<user_id>.+)/', views.BindUserTags.as_view(), name='bind-user-tags'),
    re_path('create-user-tagship/(?P<user_id>.+)/(?P<tag_id>.+)/', views.CreateUserTagship.as_view(), name='create-user-tagship'),
    re_path('delete-user-tagship/(?P<user_id>.+)/(?P<tag_id>.+)/', views.DeleteUserTagship.as_view(), name='delete-user-tagship'),

]

feedback_app/urls.py
from django.conf.urls import re_path
from . import views

app_name = 'feedback_app'
urlpatterns = [
    re_path('create-feedback/(?P<event_id>.+)/', views.CreateFeedback.as_view(), name='create-feedback'),
]

group_app/urls.py
from django.conf.urls import re_path
from django.views.generic.base import RedirectView
from . import views

app_name = 'group_app'
urlpatterns = [
    # re_path('group/(?P<group_id>.+)/', views.Group.as_view(), name='group'),
    re_path('list-posts/(?P<group_id>.+)/', views.ListPosts.as_view(), name='list-posts'),
    re_path('create-group/(?P<organization_id>.+)', views.CreateGroup.as_view(), name='create-group'),
    re_path('update-group/(?P<group_id>.+)/', views.UpdateGroup.as_view(), name='update-group'),
    re_path('delete-group/(?P<group_id>.+)/', views.DeleteGroup.as_view(), name='delete-group'),
    re_path('unbind-user-groups/(?P<user_id>.+)/', views.UnbindUserGroups.as_view(), name='unbind-user-groups'),
    re_path('bind-user-groups/(?P<user_id>.+)/', views.BindUserGroups.as_view(), name='bind-user-groups'),

    re_path('unbind-group-users/(?P<group_id>.+)/', views.UnbindGroupUsers.as_view(), name='unbind-group-users'),
    re_path('bind-group-users/(?P<group_id>.+)/', views.BindGroupUsers.as_view(), name='bind-group-users'),
    re_path('create-groupship-user/(?P<group_id>.+)/(?P<user_id>.+)/', views.CreateGroupshipUser.as_view(), name='create-groupship-user'),
    re_path('create-user-groupship/(?P<group_id>.+)/(?P<user_id>.+)/', views.CreateUserGroupship.as_view(), name='create-user-groupship'),

    re_path('set-user-groupship/(?P<group_id>.+)/(?P<user_id>.+)/', views.SetUserGroupship.as_view(), name='set-user-groupship'),
    re_path('set-groupship-user/(?P<group_id>.+)/(?P<user_id>.+)/', views.SetGroupshipUser.as_view(), name='set-groupship-user'),

    re_path('group-link/(?P<group_id>.+)/', views.GroupLink.as_view(), name='group-link'),
    re_path('pin-group/(?P<group_id>.+)/', views.PinGroup.as_view(), name='pin-group'),
    re_path('unpin/(?P<pin_id>.+)/', views.Unpin.as_view(), name='unpin'),
    re_path('select-destin-group/(?P<group_id>.+)/', views.SelectDestinGroup.as_view(), name='select-destin-group'),
    re_path('paste-post/(?P<group_id>.+)/(?P<post_id>.+)/', views.PastePost.as_view(), name='paste-post'),
    re_path('paste-all-posts/(?P<group_id>.+)/', views.PasteAllPosts.as_view(), name='paste-all-posts'),
    re_path('delete-groupship-user/(?P<group_id>.+)/(?P<user_id>.+)/', views.DeleteGroupshipUser.as_view(), name='delete-groupship-user'),
    re_path('delete-user-groupship/(?P<group_id>.+)/(?P<user_id>.+)/', views.DeleteUserGroupship.as_view(), name='delete-user-groupship'),
    re_path('join-public-group/(?P<group_id>.+)/', views.JoinPublicGroup.as_view(), name='join-public-group'),
    re_path('leave-group/(?P<group_id>.+)/', views.LeaveGroup.as_view(), name='leave-group'),

]

post_app/urls.py
from django.urls import path
from . import views

app_name = 'post_app'
urlpatterns = [
    path('post/<int:post_id>/', views.Post.as_view(), name='post'),

    path('refresh-post/<int:post_id>/', views.RefreshPost.as_view(), name='refresh-post'),

    path('post-link/<int:post_id>/', views.PostLink.as_view(), name='post-link'),

    path('done/<int:post_id>/', views.Done.as_view(), name='done'),
    path('undo/<int:post_id>/', views.Undo.as_view(), name='undo'),

    path('create-post/<int:ancestor_id>/', views.CreatePost.as_view(), name='create-post'),
    path('update-post/<int:post_id>/', views.UpdatePost.as_view(), name='update-post'),
    path('post-diff/<int:event_id>/', views.PostDiff.as_view(), name='post-diff'),

    path('attach-file/<int:post_id>/', views.AttachFile.as_view(), name='attach-file'),
    path('detach-file/<int:filewrapper_id>/', views.DetachFile.as_view(), name='detach-file'),
    path('post-file-download/<int:filewrapper_id>/', views.PostFileDownload.as_view(), name='post-file-download'),

    path('delete-post/<int:post_id>/', views.DeletePost.as_view(), name='delete-post'),
    path('delete-post/<int:post_id>/', views.DeletePost.as_view(), name='delete-post'),
    path('post-link/<int:post_id>/', views.PostLink.as_view(), name='post-link'),

    path('post-tag-information/(?P<tag_id>.+)/<int:post_id>/', views.PostTagInformation.as_view(), name='post-tag-information'),
    path('like-post/<int:post_id>/', views.LikePost.as_view(), name='like-post'),
    path('unlike-post/<int:post_id>/', views.UnlikePost.as_view(), name='unlike-post'),

    path('unbind-post-tags/<int:post_id>/', views.UnbindPostTags.as_view(), name='unbind-post-tags'),
    path('bind-post-tags/<int:post_id>/', views.BindPostTags.as_view(), name='bind-post-tags'),
    path('create-post-tagship/<int:post_id>/<int:tag_id>/', views.CreatePostTagship.as_view(), name='create-post-tagship'),
    path('delete-post-tagship/<int:post_id>/<int:tag_id>/', views.DeletePostTagship.as_view(), name='delete-post-tagship'),

    path('setup-post-filter/(?P<group_id>.+)', views.SetupPostFilter.as_view(), name='setup-post-filter'),
    path('find/', views.Find.as_view(), name='find'),

    path('cut-post/<int:post_id>/', views.CutPost.as_view(), name='cut-post'),
    path('copy-post/<int:post_id>/', views.CopyPost.as_view(), name='copy-post'),
    path('confirm-post-deletion/<int:post_id>/', views.ConfirmPostDeletion.as_view(), name='confirm-post-deletion'),
    path('select-fork-list/<int:post_id>/', views.SelectForkList.as_view(), name='select-fork-list'),
    path('create-post-fork/<int:ancestor_id>/<int:post_id>/', views.CreatePostFork.as_view(), name='create-post-fork'),
    path('pull-card-content/<int:ancestor_id>/<int:post_id>/', views.PullCardContent.as_view(), name='pull-card-content'),
    path('post-events/<int:post_id>/', views.PostEvents.as_view(), name='post-events'),
    path('pin-post/<int:post_id>/', views.PinPost.as_view(), name='pin-post'),
    path('unpin/<int:pin_id>/', views.Unpin.as_view(), name='unpin'),
    path('set-post-priority-down/<int:post0_id>/<int:post1_id>/', views.SetPostPriorityDown.as_view(), name='set-post-priority-down'),
    path('set-post-priority-up/<int:post0_id>/<int:post1_id>/', views.SetPostPriorityUp.as_view(), name='set-post-priority-up'),
    path('post-priority/<int:post_id>/', views.PostPriority.as_view(), name='post-priority'),
    path('restore-post/(?P<event_id>.+)/', views.RestorePost.as_view(), name='restore-post'),

]

group_app/models.py
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse
from core_app.models import  User, Event, Node
from sqlike.parser import SqLike, SqNode
from django.db import models
from django.db.models import Q
import datetime

class GroupMixin(models.Model):
    class Meta:
        abstract = True

    @classmethod
    def from_sqlike(cls):
        owner   = lambda ind: Q(owner__name__icontains=ind) | Q(
        owner__email__icontains=ind)
        name        = lambda ind: Q(name__icontains=ind)
        description = lambda ind: Q(description__icontains=ind)
        default     = lambda ind: Q(name__icontains=ind) \
        | Q(description__icontains=ind)

        sqlike = SqLike(cls, SqNode(None, default),
        SqNode(('o', 'owner'), owner),
        SqNode(('n', 'name'), name),
        SqNode(('d', 'description'), description),)
        return sqlike

    @classmethod
    def get_user_groups(cls, user):
        groups = user.groups.filter(
            organization=user.default)
        return groups

    def get_link_url(self):
        return reverse('group_app:group-link', 
                    kwargs={'group_id': self.id})

    def save(self, *args, **kwargs):
        if not self.pk:
            self.node = Node.objects.create()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    def revoke_access(self, admin, user):
        """
        Remove user access and allow admin access.
        """

        self.users.remove(user)
        if self.owner == user: 
            self.set_ownership(admin)

    def set_ownership(self, admin):
        self.users.add(admin)
        self.owner = admin
        self.save()            

class GroupPinMixin(models.Model):
    class Meta:
        abstract = True

    def get_absolute_url(self):
        return reverse('group_app:list-posts', 
            kwargs={'group_id': self.group.id})

class GroupPin(GroupPinMixin):
    user = models.ForeignKey('core_app.User', 
    null=True, on_delete=models.CASCADE)

    organization = models.ForeignKey('core_app.Organization', 
    null=True, on_delete=models.CASCADE)

    group = models.ForeignKey('group_app.Group', 
    null=True, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'organization', 'group')

class Groupship(models.Model):
    """    
    """
    group = models.ForeignKey('Group', null=True, on_delete=models.CASCADE)

    user = models.ForeignKey('core_app.User', null=True, on_delete=models.CASCADE,
    related_name='user_groupship')

    binder = models.ForeignKey('core_app.User', null=True, on_delete=models.CASCADE,
    related_name='binder_groupship', blank=True)

    created  = models.DateTimeField(auto_now_add=True, null=True)

    CHOICES = (
        ('0', 'Admin'),
        ('1','Member'),
        ('2','Guest'),

    )

    status = models.CharField(max_length=6, 
    choices=CHOICES, default='2')

    class Meta:
        unique_together = ('group', 'user', )

class Group(GroupMixin):
    users = models.ManyToManyField('core_app.User',
    through=Groupship, related_name='groups', blank=True, 
    through_fields=('group', 'user'), symmetrical=False)

    organization = models.ForeignKey('core_app.Organization', 
    related_name='groups', null=False, on_delete=models.CASCADE)

    open = models.BooleanField(blank=True, default=False,
    help_text='Contributors can also post over.')

    public = models.BooleanField(blank=True, default=False,
    help_text='Visible to all organization members.')

    name = models.CharField(null=True, blank=False,
    verbose_name=_("Name"), help_text='Example: Bugs', max_length=250)

    description = models.CharField(blank=True, default='', 
    verbose_name=_("Description"), help_text='Example: /projectname/', 
    max_length=626)

    owner = models.ForeignKey('core_app.User', null=True, 
    on_delete=models.CASCADE, related_name='owned_groups')

    created  = models.DateTimeField(auto_now_add=True, 
    null=True)

    node = models.OneToOneField('core_app.Node', 
    null=False, related_name='group', on_delete=models.CASCADE)

class EDeleteGroup(Event):
    group_name = models.CharField(null=True,
    blank=False, max_length=250)

    html_template = 'group_app/e-delete-group.html'

class ECreateGroup(Event):
    group = models.ForeignKey('Group', 
    related_name='e_create_group', null=True, on_delete=models.CASCADE)
    html_template = 'group_app/e-create-group.html'

class EUpdateGroup(Event):
    group = models.ForeignKey('Group', 
    related_name='e_update_group', null=True, on_delete=models.CASCADE)
    html_template = 'group_app/e-update-group.html'

class EBindGroupUser(Event):
    group = models.ForeignKey('Group', 
    related_name='e_bind_group_user', null=True, on_delete=models.CASCADE)

    peer = models.ForeignKey('core_app.User', null=True, on_delete=models.CASCADE)

    CHOICES = (
        ('0', 'Admin'),
        ('1','Member'),
        ('2','Guest'),
    )

    status = models.CharField(max_length=6, choices=CHOICES)

    html_template = 'group_app/e-bind-group-user.html'

class EUnbindGroupUser(Event):
    group = models.ForeignKey('Group', 
    related_name='e_unbind_group_user', null=True, on_delete=models.CASCADE)

    peer = models.ForeignKey('core_app.User', null=True, on_delete=models.CASCADE)
    html_template = 'group_app/e-unbind-group-user.html'

class EPastePost(Event):
    group = models.ForeignKey('group_app.Group', 
    related_name='e_paste_post0', null=True, on_delete=models.CASCADE)

    posts = models.ManyToManyField('post_app.Post',
    related_name='e_paste_post1', blank=True, symmetrical=False)
    html_template = 'group_app/e-paste-post.html'

group_app/templates/group_app/create-group.html
{% load bootstrap3 %}
{% load i18n %}

<form id="groupForm" enctype="multipart/form-data">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>

<h4 class="modal-title"> <span class="glyphicon glyphicon-eye-open"></span> Group</h4>

</div>
<div class="modal-body">
{% csrf_token %}
{% bootstrap_field form.name  size='sm' %}
{% bootstrap_field form.description  size='sm' %}
{% bootstrap_field form.open  size='sm' %}
{% bootstrap_field form.public  size='sm' %}

{% bootstrap_form_errors form type='non_fields' %}

</div>
</form>

<div class="modal-footer">
<button  type="button" data-form="#groupForm" 
data-shell="#main-view" data-show="{% url 'group_app:create-group' organization_id %}"
class="btn btn-sm btn-default e-post"> 
<span class="glyphicon glyphicon-ok"></span> {% trans "Create" %}
</button>

</div>

group_app/templates/group_app/create-groupship-user.html
{% load bootstrap3 %}
{% load i18n %}


<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h5> <span class="glyphicon glyphicon-plus"></span> Create Group Relationship</h5>
</div>

<div class="modal-body">
<p class="text-warning">  Bind {{user.name}} to the group {{group.name}}?</p>

<form id="groupshipForm" enctype="multipart/form-data">
{% csrf_token %}
{% bootstrap_field form.status  size='sm' %}
{% bootstrap_form_errors form type='non_fields' %}

</form>
<small>
<p class="text-info"> Admins can create/delete content.</p>
<p class="text-info"> Workers can create content.</p>
<p class="text-info"> Guests can feedback on events and receive notification..</p>
</small>

</div>

<div class="modal-footer">

<button  type="button" class="btn btn-default e-get" data-show="{% url 'group_app:bind-group-users' group.id %}"> {% trans "Back" %} </button>

<button  type="button" data-dismiss="modal" class="btn btn-default"> 
     {% trans "Cancel" %}
</button>

<button  type="button" data-form="#groupshipForm" data-show="{% url 'group_app:create-groupship-user' group.id user.id  %}"
class="btn btn-default e-post"> {% trans "Done" %} </button>

</div>

group_app/templates/group_app/delete-groupship-user.html
{% load bootstrap3 %}
{% load i18n %}


<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h5> <span class="glyphicon glyphicon-cog"></span> Remove group Relationship</h5>
</div>

<div class="modal-body">
<p class="text-warning"> Remove {{user.name}} status on group {{group.name}}? </p>

<form id="groupshipForm" enctype="multipart/form-data">
{% csrf_token %}
</form>

</div>

<div class="modal-footer">
<div class="btn-group btn-group-sm">

<button  type="button" class="btn btn-default e-get" data-show="{% url 'group_app:unbind-group-users' group.id %}"> 
<span class="glyphicon glyphicon-arrow-left"></span> {% trans "Back" %} </button>

<button  type="button" data-dismiss="modal" class="btn btn-default"> 
<span class="glyphicon glyphicon-thumbs-down"></span> {% trans "Cancel" %}
</button>

<button  type="button" data-form="#groupshipForm"  
data-show="{% url 'group_app:delete-groupship-user' group.id user.id  %}"
class="btn btn-default e-post"> <span class="glyphicon glyphicon-ok"></span> {% trans "Done" %} </button>
</div>

</div>

group_app/templates/group_app/set-groupship-user.html
{% load bootstrap3 %}
{% load i18n %}


<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h5> <span class="glyphicon glyphicon-cog"></span> Set Group Relationship</h5>
</div>

<div class="modal-body">
<p class="text-warning"> Change {{user.name}} status on group {{group.name}}? </p>

<form id="groupshipForm" enctype="multipart/form-data">
{% csrf_token %}
{% bootstrap_field form.status  size='sm' %}
{% bootstrap_form_errors form type='non_fields' %}

</form>

{% if user.id == me.id %}
<a class="e-get" data-shell="#smallModalContent" 
data-show="{% url 'group_app:leave-group' group.id %}" 
href="#"> <span class="glyphicon glyphicon-thumbs-down"></span> 
{% trans "Leave?" %}</a>

{% else %}
<a href="#" data-show="{% url 'group_app:delete-groupship-user' group.id user.id %}" class="e-get text-warning"> 
 <span class="glyphicon glyphicon-remove"></span> Remove {{user.name}}? </a>
{% endif %}

</div>

<div class="modal-footer">

<div class="btn-group btn-group-sm">
<button  type="button" class="btn btn-default e-get" data-show="{% url 'group_app:unbind-group-users' group.id %}"> 
<span class="glyphicon glyphicon-arrow-left"></span> {% trans "Back" %} </button>

<button  type="button" data-dismiss="modal" class="btn btn-default"> 
<span class="glyphicon glyphicon-thumbs-down"></span> {% trans "Cancel" %}
</button>

<button  type="button" data-form="#groupshipForm"  
data-show="{% url 'group_app:set-groupship-user' group.id user.id  %}"
class="btn btn-default e-post"> <span class="glyphicon glyphicon-ok"></span> {% trans "Done" %} </button>
</div>

</div>

group_app/templates/group_app/unbind-group-users.html
{% load bootstrap3 %}
{% load i18n %}
{% load static %}
{% load avatar %}


<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h5>
<span class="glyphicon glyphicon-search"></span>
{{group.name|truncatechars:20}}'s Members 
<span class="badge">{{count}}/{{total}}</span>
</h5>
</div>

<div class="modal-body">

<div class="pre-scrollable">
{% for ind in included %}
<p class="text-center">
<img class="img-responsive center-block"  width="50" height="50"  src="{% avatar ind.avatar %}" />
{{ind.name}}  
<br>

<small> {{ind.email}} </small>   <br>

<a class="e-get" style="font-size:70%"  data-show="{% url 'group_app:set-groupship-user' group.id ind.id %}" href="#"> 
<span class="glyphicon glyphicon-cog"></span> Settings</a>  

</p>

{% endfor %}

</div>

<br>

<form id="userSearchForm" enctype="multipart/form-data">
{% csrf_token %}
{% bootstrap_field form.pattern  size='md' layout='inline' %}
{% bootstrap_form_errors form type='non_fields' %}
</form>

<a href="#" data-show="{% url 'group_app:bind-group-users' group.id %}" class="e-get"> 
 <span class="glyphicon glyphicon-send"></span> Bind Users? </a>

</div>


<div class="modal-footer">
<div class="btn-group btn-group-sm">

<button type="button" data-form="#userSearchForm" 
data-show="{% url 'group_app:unbind-group-users' group.id  %}"
class="btn btn-default e-post"> <span class="glyphicon glyphicon-search"></span>
{% trans "Search" %} </button>

<button  type="button" data-dismiss="modal" class="btn btn-default"> 
<span class="glyphicon glyphicon-thumbs-down"></span> {% trans "Close" %}
</button>
</div>

</div>

group_app/templates/group_app/unbind-user-groups.html
{% load bootstrap3 %}
{% load i18n %}


<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h5>
<span class="glyphicon glyphicon-search"></span>
{{user.name}}'s Groups <span class="badge">{{count}}/{{total}}</span> </h5>
</div>

<div class="modal-body">

<div class="pre-scrollable">
{% for ind in included %}
<p class="text-center">

<b><span class="glyphicon glyphicon-eye-open"></span> {{ind.name}} </b>
{{ind.description}}

<br> <a class="e-get" style="font-size:70%"  data-show="{% url 'group_app:set-user-groupship' ind.id user.id %}" href="#"> 
<span class="glyphicon glyphicon-cog"></span> Settings</a>  

</p>
{% empty %}
<p> ... </p>

{% endfor %}

</div>

<br> 
<form id="groupSearchForm" enctype="multipart/form-data">
{% csrf_token %}
{% bootstrap_field form.pattern  size='md' layout='inline' %}
{% bootstrap_form_errors form type='non_fields' %}
</form>

<a href="#" data-show="{% url 'group_app:bind-user-groups' user.id %}" class="e-get"> 
 <span class="glyphicon glyphicon-send"></span> Bind Groups? </a>

</div>

<div class="modal-footer">
<div class="btn-group btn-group-sm">

<button  type="button" 
data-shell="#smallModalContent" data-show="{% url 'core_app:list-users'  %}"
class="btn btn-default e-get"> 
<span class="glyphicon glyphicon-arrow-left"></span> {% trans "Back" %} </button>

<button  type="button" data-form="#groupSearchForm" data-shell="#smallModalContent" 
data-show="{% url 'group_app:unbind-user-groups' user.id  %}"
class="btn btn-default e-post"> <span class="glyphicon glyphicon-search"></span> {% trans "Search" %} </button>

<button  type="button" data-dismiss="modal" class="btn btn-default"> 
<span class="glyphicon glyphicon-thumbs-down"></span> {% trans "Close" %}
</button>
</div>

</div>