arcamens/urls.py
from django.urls import path, include
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
    path(r'admin/', admin.site.urls),
     path(r'core_app/', include('core_app.urls')),
     path(r'group_app/', include('group_app.urls')),
     path(r'board_app/', include('board_app.urls')),
     path(r'feedback_app/', include('feedback_app.urls')),
     path(r'site_app/', include('site_app.urls')),
     path(r'cash_app/', include('cash_app.urls')),

     path(r'post_app/', include('post_app.urls', namespace='post_app')),
     path(r'paybills/', include('paybills.urls')),
     path(r'onesignal/', include('onesignal.urls')),
    path(r'card_app/', include('card_app.urls')),
    path(r'comment_app/', include('comment_app.urls')),
    path(r'note_app/', include('note_app.urls')),
    path(r'jscroll/', include('jscroll.urls')),

    path(r'bitbucket_app/', include('bitbucket_app.urls')),
    path(r'github_app/', include('github_app.urls')),

    path(r'list_app/', include('list_app.urls')),

    path(r'', RedirectView.as_view(pattern_name='site_app:index')),
]


# handler500 = 'core_app.views.default_error'

card_app/urls.py
from django.conf.urls import re_path
from . import views

app_name = 'card_app'
urlpatterns = [
    re_path('list-cards/(?P<list_id>.+)/', views.ListCards.as_view(), name='list-cards'),
    re_path('cut-card/(?P<card_id>.+)/', views.CutCard.as_view(), name='cut-card'),
    re_path('refresh-card-label/(?P<card_id>.+)/', views.RefreshCardLabel.as_view(), name='refresh-card-label'),

    re_path('done/(?P<card_id>.+)/', views.Done.as_view(), name='done'),
    re_path('undo/(?P<card_id>.+)/', views.Undo.as_view(), name='undo'),
    re_path('archive-all/(?P<list_id>.+)/', views.ArchiveAll.as_view(), name='archive-all'),

    re_path('card-worker-information/(?P<peer_id>.+)/(?P<card_id>.+)/', views.CardWorkerInformation.as_view(), name='card-worker-information'),
    re_path('card-tag-information/(?P<tag_id>.+)/(?P<card_id>.+)/', views.CardTagInformation.as_view(), name='card-tag-information'),
    re_path('card-link/(?P<card_id>.+)/', views.CardLink.as_view(), name='card-link'),
    re_path('select-fork-list/(?P<card_id>.+)/', views.SelectForkList.as_view(), name='select-fork-list'),

    re_path('create-card/(?P<ancestor_id>.+)/', views.CreateCard.as_view(), name='create-card'),

    re_path('create-fork/(?P<ancestor_id>.+)/(?P<card_id>.+)/', views.CreateFork.as_view(), name='create-fork'),
    re_path('pull-card-content/(?P<ancestor_id>.+)/(?P<card_id>.+)/', views.PullCardContent.as_view(), name='pull-card-content'),

    re_path('attach-file/(?P<card_id>.+)/', views.AttachFile.as_view(), name='attach-file'),
    re_path('detach-file/(?P<filewrapper_id>.+)/', views.DetachFile.as_view(), name='detach-file'),
    re_path('card-file-download/(?P<filewrapper_id>.+)/', views.CardFileDownload.as_view(), name='card-file-download'),

    re_path('delete-card/(?P<card_id>.+)/', views.DeleteCard.as_view(), name='delete-card'),
    re_path('view-data/(?P<card_id>.+)/', views.ViewData.as_view(), name='view-data'),
    re_path('card-diff/(?P<event_id>.+)/', views.CardDiff.as_view(), name='card-diff'),

    re_path('confirm-card-deletion/(?P<card_id>.+)/', views.ConfirmCardDeletion.as_view(), name='confirm-card-deletion'),
    re_path('set-deadline/(?P<card_id>.+)/', views.SetDeadline.as_view(), name='set-deadline'),

    re_path('update-card/(?P<card_id>.+)/', views.UpdateCard.as_view(), name='update-card'),
    re_path('restore-card/(?P<event_id>.+)/', views.RestoreCard.as_view(), name='restore-card'),

    re_path('alert-card-workers/(?P<card_id>.+)/', views.AlertCardWorkers.as_view(), name='alert-card-workers'),


    re_path('cut-card/(?P<card_id>.+)/', views.CutCard.as_view(), name='cut-card'),
    re_path('copy-card/(?P<card_id>.+)/', views.CopyCard.as_view(), name='copy-card'),
    re_path('setup-card-filter/(?P<list_id>.+)', views.SetupCardFilter.as_view(), name='setup-card-filter'),
    re_path('pin-card/(?P<card_id>.+)/', views.PinCard.as_view(), name='pin-card'),
    re_path('request-card-attention/(?P<peer_id>.+)/(?P<card_id>.+)', views.RequestCardAttention.as_view(), name='request-card-attention'),
    re_path('find/', views.Find.as_view(), name='find'),
    re_path('card-events/(?P<card_id>.+)/', views.CardEvents.as_view(), name='card-events'),
    re_path('unpin/(?P<pin_id>.+)/', views.Unpin.as_view(), name='unpin'),
    re_path('card-priority/(?P<card_id>.+)/', views.CardPriority.as_view(), name='card-priority'),

    re_path('set-card-priority-down/(?P<card0_id>.+)/(?P<card1_id>.+)/', views.SetCardPriorityDown.as_view(), name='set-card-priority-down'),
    re_path('set-card-priority-up/(?P<card0_id>.+)/(?P<card1_id>.+)/', views.SetCardPriorityUp.as_view(), name='set-card-priority-up'),

    re_path('unbind-card-workers/(?P<card_id>.+)/', views.UnbindCardWorkers.as_view(), name='unbind-card-workers'),
    re_path('bind-card-users/(?P<card_id>.+)/', views.BindCardWorkers.as_view(), name='bind-card-workers'),
    re_path('create-card-taskship-user/(?P<card_id>.+)/(?P<user_id>.+)/', views.CreateCardTaskshipUser.as_view(), name='create-card-taskship-user'),
    re_path('delete-card-taskship-user/(?P<card_id>.+)/(?P<user_id>.+)/', views.DeleteCardTaskshipUser.as_view(), name='delete-card-taskship-user'),

    re_path('unbind-card-tags/(?P<card_id>.+)/', views.UnbindCardTags.as_view(), name='unbind-card-tags'),
    re_path('bind-card-tags/(?P<card_id>.+)/', views.BindCardTags.as_view(), name='bind-card-tags'),
    re_path('create-card-tagship/(?P<card_id>.+)/(?P<tag_id>.+)/', views.CreateCardTagship.as_view(), name='create-card-tagship'),
    re_path('delete-card-tagship/(?P<card_id>.+)/(?P<tag_id>.+)/', views.DeleteCardTagship.as_view(), name='delete-card-tagship'),

]

note_app/urls.py
from django.urls import path
from . import views

app_name = 'note_app'
urlpatterns = [
    path('create-note/<int:card_id>/', views.CreateNote.as_view(), name='create-note'),
    path('list-notes/<int:card_id>/', views.ListNotes.as_view(), name='list-notes'),
    path('note-link/<int:note_id>/', views.NoteLink.as_view(), name='note-link'),
    path('restore-note/<int:event_id>/', views.RestoreNote.as_view(), name='restore-note'),

    path('update-note/<int:note_id>/', views.UpdateNote.as_view(), name='update-note'),
    path('note-diff/<int:event_id>/', views.NoteDiff.as_view(), name='note-diff'),

    path('preview-note/<int:note_id>/', views.PreviewNote.as_view(), name='preview-note'),

    path('note/<int:note_id>/', views.Note.as_view(), name='note'),
    path('delete-note/<int:note_id>/', views.DeleteNote.as_view(), name='delete-note'),

    path('attach-file/<int:note_id>/', views.AttachFile.as_view(), name='attach-file'),
    path('detach-file/<int:filewrapper_id>/', views.DetachFile.as_view(), name='detach-file'),
    path('note-file-download/<int:filewrapper_id>/', views.NoteFileDownload.as_view(), name='note-file-download'),
    path('find/', views.Find.as_view(), name='find'),
    path('note-events/<int:note_id>/', views.NoteEvents.as_view(), name='note-events'),

]

note_app/forms.py
from core_app.forms import FileAttachment
from sqlike.forms import SqLikeForm
from django import forms
from . import models

class NoteForm(forms.ModelForm):
    data = forms.CharField(strip=False, widget=forms.Textarea)
    class Meta:
        model  = models.Note
        exclude = ('card', 'owner')

class NoteFileWrapperForm(FileAttachment, forms.ModelForm):
    class Meta:
        model  = models.NoteFileWrapper
        fields = ('file', )

class NoteSearchForm(SqLikeForm, forms.ModelForm):
    class Meta:
        model  = models.NoteSearch
        exclude = ('user', 'organization')

note_app/views.py
from django.views.generic import View
from django.conf import settings
from django.db.models import Q
from django.shortcuts import render, redirect
from core_app.views import GuardianView, FileDownload
from jscroll.wrappers import JScroll
from django.http import HttpResponse
from card_app.models import Card
from core_app.models import User, Event
from note_app.models import Note, NoteSearch, ERestoreNote, EUpdateNote
from . import models
from . import forms

class Note(GuardianView):
    def get(self, request, note_id):
        note = models.Note.locate(self.me, self.me.default, note_id)
        attachments = note.notefilewrapper_set.all()

        return render(request, 'note_app/note.html', 
        {'note': note, 'attachments': attachments})

class NoteLink(GuardianView):
    def get(self, request, note_id):
        note = models.Note.locate(self.me, self.me.default, note_id)
        organizations = self.me.organizations.exclude(id=self.me.default.id)

        return render(request, 'note_app/note-link.html', 
        {'note': note, 'card': note.card, 'user': self.me, 
        'organizations': organizations, 'default': self.me.default, 
        'organization': self.me.default, 'settings': settings})

class ListNotes(GuardianView):
    def get(self, request, card_id):
        card = Card.locate(self.me, self.me.default, card_id)
        notes = card.notes.all().order_by('-created')

        return render(request, 'note_app/list-notes.html', 
        {'records': notes, 'card': card})

class CreateNote(GuardianView):
    """
    """

    def get(self, request, card_id):
        card = Card.locate(self.me, self.me.default, card_id)
        form = forms.NoteForm()
        return render(request, 'note_app/create-note.html', 
        {'form':form, 'card': card})

    def post(self, request, card_id):
        card = Card.locate(self.me, self.me.default, card_id)
        form = forms.NoteForm(request.POST)
        user = User.objects.get(id=self.user_id)

        if not form.is_valid():
            return render(request, 'note_app/create-note.html', 
                {'form': form, 'card':card}, status=400)

        note       = form.save(commit=False)
        note.owner = self.me
        note.card  = card
        note.save()

        event = models.ECreateNote.objects.create(
        organization=self.me.default, child=card, user=self.me, note=note)
        event.dispatch(*card.ancestor.ancestor.members.all())

        return render(request, 'note_app/preview-note.html',
        {'note': note, 'card': note.card})

class AttachFile(GuardianView):
    """
    """

    def get(self, request, note_id):
        note = models.Note.locate(self.me, self.me.default, note_id)
        attachments = note.notefilewrapper_set.all()
        form = forms.NoteFileWrapperForm()

        return render(request, 'note_app/attach-file.html', 
        {'note':note, 'form': form, 'attachments': attachments})

    def post(self, request, note_id):
        note = models.Note.locate(self.me, self.me.default, note_id)
        note = models.Note.objects.get(id=note_id)
        attachments = note.notefilewrapper_set.all()

        form = forms.NoteFileWrapperForm(request.POST, 
        request.FILES, user=self.me)

        if not form.is_valid():
            return render(request, 'note_app/attach-file.html', 
                {'note':note, 'form': form, 'attachments': attachments})
        record = form.save(commit = False)
        record.organization = self.me.default
        record.note = note
        form.save()

        event = models.EAttachNoteFile.objects.create(
        organization=self.me.default, filewrapper=record, 
        note=note, user=self.me)

        event.dispatch(*note.card.ancestor.ancestor.members.all())
        event.save()

        return self.get(request, note_id)

class DetachFile(GuardianView):
    """
    """

    def get(self, request, filewrapper_id):
        filewrapper = models.NoteFileWrapper.objects.filter(
        Q(note__card__ancestor__ancestor__members=self.me) | Q(note__card__workers=self.me), 
        note__card__ancestor__ancestor__organization=self.me.default, 
        id=filewrapper_id).distinct().first()

        attachments = filewrapper.note.notefilewrapper_set.all()
        form        = forms.NoteFileWrapperForm()

        event = models.EDettachNoteFile.objects.create(
        organization=self.me.default, filename=filewrapper.file.name, 
        note=filewrapper.note, user=self.me)

        event.dispatch(*filewrapper.note.card.ancestor.ancestor.members.all())
        event.save()
        filewrapper.delete()

        return render(request, 'note_app/attach-file.html', 
        {'note':filewrapper.note, 'form': form, 'attachments': attachments})

class PreviewNote(GuardianView):
    def get(self, request, note_id):
        note = models.Note.locate(self.me, self.me.default, note_id)
        
        return render(request, 'note_app/preview-note.html',
        {'note': note, 'card': note.card})

class UpdateNote(GuardianView):
    def get(self, request, note_id):
        note = models.Note.locate(self.me, self.me.default, note_id)
        return render(request, 'note_app/update-note.html',
        {'note': note, 'form': forms.NoteForm(instance=note),})

    def post(self, request, note_id):
        record = models.Note.locate(self.me, self.me.default, note_id)

        event = models.EUpdateNote.objects.create(note_data=record.data,
        organization=self.me.default, child=record.card, note_html=record.html,
        note=record, user=self.me)

        form = forms.NoteForm(request.POST, instance=record)

        if not form.is_valid():
            return render(request, 'note_app/update-note.html',
                        {'form': form, 'note':record, }, status=400)

        record.save()
        event.dispatch(*record.card.ancestor.ancestor.members.all())
        event.save()

        return redirect('note_app:preview-note', 
        note_id=record.id)

class DeleteNote(GuardianView):
    def post(self, request, note_id):
        note = models.Note.locate(self.me, self.me.default, note_id)

        event = models.EDeleteNote.objects.create(organization=self.me.default,
        child=note.card, note='Note', user=self.me)

        event.dispatch(*note.card.ancestor.ancestor.members.all())
        note.delete()

        # user.ws_sound(note.card.ancestor.ancestor)

        return redirect('note_app:list-notes', 
        card_id=note.card.id)

class NoteFileDownload(FileDownload):
    def get(self, request, filewrapper_id):
        filewrapper = models.NoteFileWrapper.objects.filter(
        Q(note__card__ancestor__ancestor__members=self.me) | Q(note__card__workers=self.me), 
        note__card__ancestor__ancestor__organization=self.me.default, 
        id=filewrapper_id).distinct().first()

        return self.get_file_url(filewrapper.file)

class NoteDiff(GuardianView):
    def get(self, request, event_id):
        event = models.EUpdateNote.objects.get(id=event_id)
        note = models.Note.locate(self.me, self.me.default, event.note.id)


        return render(request, 'note_app/note-diff.html', 
        {'note': note, 'event': event, 'card': note.card})

class Find(GuardianView):
    def get(self, request):
        filter, _ = NoteSearch.objects.get_or_create(
        user=self.me, organization=self.me.default)

        form   = forms.NoteSearchForm(instance=filter)

        notes = models.Note.objects.filter(
        Q(card__ancestor__ancestor__members=self.me) &
        Q(card__ancestor__ancestor__organization=self.me.default) |\
        Q(card__workers=self.me)).distinct()

        total  = notes.count()

        sqlike = models.Note.from_sqlike()

        sqlike.feed(filter.pattern)

        notes = sqlike.run(notes)
        count = notes.count()

        notes = notes.only('card__label', 'card__id', 'data', 'id').order_by('id')
        elems = JScroll(self.me.id, 'note_app/find-scroll.html', notes)

        return render(request, 'note_app/find.html', 
        {'form': form, 'elems':  elems.as_div(), 'total': total, 'count': count})

    def post(self, request):
        filter, _ = NoteSearch.objects.get_or_create(
        user=self.me, organization=self.me.default)

        sqlike = models.Note.from_sqlike()
        form  = forms.NoteSearchForm(request.POST, sqlike=sqlike, instance=filter)

        notes = models.Note.objects.filter(
        Q(card__ancestor__ancestor__members=self.me) &
        Q(card__ancestor__ancestor__organization=self.me.default) |\
        Q(card__workers=self.me)).distinct()

        total = notes.count()

        if not form.is_valid():
            return render(request, 'note_app/find.html', 
                {'form': form, 'total': total, 'count': 0}, status=400)
        form.save()

        notes = sqlike.run(notes)

        count =  notes.count()
        notes = notes.only('card__label', 'card__id', 'data', 'id').order_by('id')
        elems = JScroll(self.me.id, 'note_app/find-scroll.html', notes)

        return render(request, 'note_app/find.html', 
        {'form': form, 'elems':  elems.as_div(), 'total': total, 'count': count})


class RestoreNote(GuardianView):
    def post(self, request, event_id):
        event = EUpdateNote.objects.get(id=event_id)
        note  = models.Note.locate(self.me, self.me.default, event.note.id)

        note.data = event.note_data
        note.save()

        event = models.ERestoreNote.objects.create(
        event_html=event.html, organization=self.me.default, 
        card=note.card, note=note, user=self.me)

        event.dispatch(*note.card.ancestor.ancestor.members.all())
        event.save()
        return redirect('note_app:preview-note', note_id=note.id)

class NoteEvents(GuardianView):
    def get(self, request, note_id):
        note = models.Note.locate(self.me, self.me.default, note_id)

        query = Q(ecreatenote__note__id=note.id) | \
        Q(eupdatenote__note__id=note.id) |\

note_app/templates/note_app/create-note.html
{% load bootstrap3 %}
{% load i18n %}

<form id="noteForm" enctype="multipart/form-data">

<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h4> 
<span class="glyphicon glyphicon glyphicon-bell"></span>
 Note </h4>
</div>

<div class="modal-body">

{% csrf_token %}

{% bootstrap_field form.data  size='md' %}
{% bootstrap_form_errors form type='non_fields' %}

</div>
</form>


<div class="modal-footer">
{% block buttons %}

<button  type="button" data-show="{% url 'note_app:list-notes' card.id %}"
class="btn btn-default e-get"> 
     {% trans "Back" %}
</button>

<button  type="button" data-form="#noteForm" 
data-show="{% url 'note_app:create-note' card.id %}"
class="btn btn-default e-post"> 
     {% trans "Create" %}
</button>
{% endblock %}
</div>

note_app/templates/note_app/e-delete-note.html
{% extends 'group_app/event.html' %}
{% load i18n %}

{% block content %}
<a href="#" data-toggle="popover" data-trigger="hover" title="{{event.user.email}}"  data-content="{{event.user.description}}">

<span class="glyphicon glyphicon-user"></span>
{{event.user}} </a> has deleted 

<span style="color:red">
<span class="glyphicon glyphicon-book"></span> Note 
</span>

on

<a class="e-get"
data-shell="#bigModalContent"
data-show="{% url 'card_app:view-data' event.child.id %}" 
href="{{event.child.get_link_url}}"> 
<span class="glyphicon glyphicon-file"></span>
{{event.child.label|truncatechars:40}} </a> 

{% endblock %}

note_app/templates/note_app/e-restore-note.html
{% extends 'group_app/event.html' %}
{% load i18n %}

{% block content %}
<a class="e-get" data-shell="#bigModalContent" data-show="{% url 'note_app:preview-note' event.note.id %}"  href="{{event.note.get_link_url}}"> 
<span class="glyphicon glyphicon-bell"></span> Note </a> 
was restored on card

<a class="e-get" data-shell="#bigModalContent"
data-show="{% url 'card_app:view-data' event.card.id %}" href="{{event.card.get_link_url}}"> 
<span class="glyphicon glyphicon-file"></span>
{{event.card.label|truncatechars:50}} </a> ... from

<div class="panel panel-default">
<div class="panel-body">
{{event.event_html|safe}}
</div>
</div>

{% endblock %}

note_app/templates/note_app/e-update-note.html
{% extends 'group_app/event.html' %}
{% load i18n %}

{% block content %}
<a class="e-get"
data-shell="#bigModalContent" 
data-show="{% url 'note_app:preview-note' event.note.id %}" 
href="{{event.note.get_link_url}}"> 
<span class="glyphicon glyphicon-book"></span> Note </a>  ...
<a class="e-get"
data-shell="#bigModalContent"
data-show="{% url 'note_app:note-diff' event.id %}" 
href="{{event.note.get_link_url}}"> 
<span class="glyphicon glyphicon-check"></span> Diff </a>?

was updated on

<a class="e-get"
data-shell="#bigModalContent"
data-show="{% url 'card_app:view-data' event.child.id %}" 
href="{{event.child.get_link_url}}"> 
<span class="glyphicon glyphicon-file"></span>
{{event.child.label|truncatechars:40}} </a> 

{% endblock %}

note_app/templates/note_app/find-scroll.html
{% for ind in elems %}
<div class="panel panel-default">
<div class="panel-body">

<pre>
{{ind.data|truncatechars:300}}
</pre>
<small>
<a class="e-get" href="{{ind.get_link_url}}" data-show="{% url 'note_app:preview-note' ind.id %}"> 
<span class="glyphicon glyphicon-bell"></span>
Note </a> on card <a href="{{ind.card.get_link_url}}" data-shell="#bigModalContent" data-show="{% url 'card_app:view-data' ind.card.id %}"
class="e-get">  <span class="glyphicon glyphicon-file"></span> {{ind.card.label|truncatechars:60}} </a>
</small>
</div>
</div>

{% endfor %}

note_app/templates/note_app/find.html
{% load bootstrap3 %}
{% load i18n %}


<div id="view-data">
<div class="modal-header">
<button type="button"  class="close" data-dismiss="modal">&times;</button>
<h4> 
<span class="glyphicon glyphicon-search"></span>

Notes
<span class="badge">{{count}}/{{total}}</span><h4>
</div>

<div class="modal-body">
<div class="pre-scrollable"> {{elems | safe}} </div>

<hr>

<form id="noteSearchForm" enctype="multipart/form-data">
{% csrf_token %}
{% bootstrap_field form.pattern  size='md'  %}

{% bootstrap_form_errors form type='non_fields' %}
</form>
</div>

</div>
</div>

<div class="modal-footer">
<button  type="button" data-form="#noteSearchForm"  data-show="{% url 'note_app:find'  %}"
class="btn btn-default e-post"> {% trans "Filter" %} </button>

<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>

note_app/templates/note_app/note-diff.html
{% load bootstrap3 %}
{% load i18n %}

<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<span class="glyphicon glyphicon-file"></span> Change by 
<a href="#" data-toggle="popover" data-trigger="hover" title="{{event.user.email}}"  data-content="{{event.user.description}}"> {{event.user.name}} </a> 

</a>
on <a class="e-get"
data-shell="#bigModalContent"
data-show="{% url 'note_app:preview-note' note.id %}" 
href="{{event.note.get_link_url}}"> 
<span class="glyphicon glyphicon-file"></span> Note </a>

from card <a class="e-get"
data-shell="#bigModalContent"
data-show="{% url 'card_app:view-data' card.id %}" 
href="{{event.card.get_link_url}}"> 
<span class="glyphicon glyphicon-file"></span> {{card.label|truncatechars:40}} </a>

</div>

<div class="modal-body">
<div class="panel panel-default">

<div class="panel-body">
{{event.note_html | safe}}

<form id="restoreNoteForm"> {% csrf_token %} </form>
<a href="#" data-shell="#bigModalContent" data-form="#restoreNoteForm"  data-show="{% url 'note_app:restore-note' event.id  %}"
class="e-post"> <span class="glyphicon glyphicon-repeat"></span> Restore changes? </a>

</div>


</div>

<script>
$(function () {
    $('[data-toggle="popover"]').popover()
})
</script>

</div>

note_app/templates/note_app/note-link.html
{% extends 'core_app/index.html' %}

{% load i18n %}
{% load static %}

{% block initializer %}
<script>
$(document).ready(function() {
    $('#main-view').load("{% url 'card_app:list-cards' card.ancestor.id %}");
    $('#bigModalContent').load("{% url 'note_app:preview-note' note.id %}");
    $('#bigModal').modal('show');

});

$(function () {
    $('[data-toggle="popover"]').popover()
})
</script>
{% endblock %}

note_app/templates/note_app/note-menu-actions.html
<div class="dropdown">
  <a class="dropdown-toggle" type="button" data-toggle="dropdown">
  <span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li><a href="#">Update</a></li>
    <li><a href="#">Remove</a></li>
  </ul>
</div>

note_app/templates/note_app/note.html
{% load bootstrap3 %}
{% load i18n %}
{% load static %}

<div class="panel panel-default">
<div class="panel-body">
<form id="deleteNoteForm"> {% csrf_token %} </form>
<p style="font-size:80%"> 
<span class="glyphicon glyphicon-bell"></span> 

By 
<a href="#" data-toggle="popover" data-trigger="hover" title="{{note.owner.email}}"  data-content="{{note.owner.description}}"> {{note.owner.name}} </a>
on <a href="{{note.get_link_url}}" target="_blank"> {{note.created}} </a>

</p>

<div style="word-wrap: break-word;"> 

{{note.html | safe}}

</div>

<span  style="font-size:80%">
<div id="note-attachments-{{note.id}}" style="min-height:50px;"> </div>

<script> 
$.get({ 
url: "{% url 'note_app:attach-file' note.id %}",
async: true},

function(data) {
    $('#note-attachments-{{note.id}}').html(data);
});

$(function () {
    $('[data-toggle="popover"]').popover()
})

</script> 

</span>

<br>
<a data-show="{% url 'note_app:note-events' note.id %}" href="#"
data-shell="#mediumModalContent" class="e-get"> <span class="glyphicon glyphicon-bell"></span> 
{% trans "Activity" %} </a>

<a href="#"
data-show="{% url 'note_app:update-note' note.id %}"
data-shell="#bigModalContent" 
class="text-warning e-get"> 
<span class="glyphicon glyphicon-edit"></span> 
{% trans "Update" %} </a>

<a href="#" data-form="#deleteNoteForm" data-show="{% url 'note_app:delete-note' note.id %}" data-shell="#bigModalContent" class="text-danger e-post"> 
<span class="glyphicon glyphicon-remove"></span> 

{% trans "Remove" %} </a>

</div>


</div>

note_app/templates/note_app/preview-note.html
{% load bootstrap3 %}
{% load static %}

{% load i18n %}

<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<span class="glyphicon glyphicon-bell"></span> 
Note on card 

<a href="{{card.get_link_url}}" data-shell="#bigModalContent" data-show="{% url 'card_app:view-data' card.id %}"
class="e-get">  <span class="glyphicon glyphicon-file"></span> {{card.label|truncatechars:60}} </a>

<a href="#" data-shell="#bigModalContent" data-show="{% url 'note_app:find' %}"
class="e-get">  <span class="glyphicon glyphicon-search"></span> Notes </a>
</div>

<div class="modal-body pre-scrollable">
{% include 'note_app/note.html' %}
</div>

<div class="modal-footer" >
<button  type="button" 
data-show="{% url 'note_app:list-notes' card.id %}"
data-shell="#bigModalContent" 
class="btn btn-default e-get"> {% trans "Notes" %} </button>

<button  type="button" data-dismiss="modal" class="btn btn-default"> 
     {% trans "Close" %}
</button>

</div>