arcamens/urls.py
from django.urls import path, include
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
    path(r'admin/', admin.site.urls),
     path(r'core_app/', include('core_app.urls')),
     path(r'group_app/', include('group_app.urls')),
     path(r'board_app/', include('board_app.urls')),
     path(r'feedback_app/', include('feedback_app.urls')),
     path(r'site_app/', include('site_app.urls')),
     path(r'cash_app/', include('cash_app.urls')),

     path(r'post_app/', include('post_app.urls', namespace='post_app')),
     path(r'paybills/', include('paybills.urls')),
     path(r'onesignal/', include('onesignal.urls')),
    path(r'card_app/', include('card_app.urls')),
    path(r'comment_app/', include('comment_app.urls')),
    path(r'note_app/', include('note_app.urls')),
    path(r'jscroll/', include('jscroll.urls')),

    path(r'bitbucket_app/', include('bitbucket_app.urls')),
    path(r'github_app/', include('github_app.urls')),

    path(r'list_app/', include('list_app.urls')),

    path(r'', RedirectView.as_view(pattern_name='site_app:index')),
]


# handler500 = 'core_app.views.default_error'

comment_app/urls.py
from django.urls import path
from . import views

app_name = 'comment_app'

urlpatterns = [
    path('create-comment/<int:post_id>/', views.CreateComment.as_view(), name='create-comment'),
    path('update-comment/<int:comment_id>/', views.UpdateComment.as_view(), name='update-comment'),
    path('comment/<int:comment_id>/', views.Comment.as_view(), name='comment'),
    path('delete-comment/<int:comment_id>/', views.DeleteComment.as_view(), name='delete-comment'),

    path('attach-file/<int:comment_id>/', views.AttachFile.as_view(), name='attach-file'),
    path('detach-file/<int:filewrapper_id>/', views.DetachFile.as_view(), name='detach-file'),
    path('comment-file-download/<int:filewrapper_id>/', views.CommentFileDownload.as_view(), name='comment-file-download'),
    path('comment-diff/<int:event_id>/', views.CommentDiff.as_view(), name='comment-diff'),
    path('restore-comment/<int:event_id>/', views.RestoreComment.as_view(), name='restore-comment'),
    path('comment-events/<int:comment_id>/', views.CommentEvents.as_view(), name='comment-events'),

    path('comment-link/<int:comment_id>/', views.CommentLink.as_view(), name='comment-link'),
    path('find/', views.Find.as_view(), name='find'),

]

post_app/urls.py
from django.urls import path
from . import views

app_name = 'post_app'
urlpatterns = [
    path('post/<int:post_id>/', views.Post.as_view(), name='post'),

    path('refresh-post/<int:post_id>/', views.RefreshPost.as_view(), name='refresh-post'),

    path('post-link/<int:post_id>/', views.PostLink.as_view(), name='post-link'),

    path('done/<int:post_id>/', views.Done.as_view(), name='done'),
    path('undo/<int:post_id>/', views.Undo.as_view(), name='undo'),

    path('create-post/<int:ancestor_id>/', views.CreatePost.as_view(), name='create-post'),
    path('update-post/<int:post_id>/', views.UpdatePost.as_view(), name='update-post'),
    path('post-diff/<int:event_id>/', views.PostDiff.as_view(), name='post-diff'),

    path('attach-file/<int:post_id>/', views.AttachFile.as_view(), name='attach-file'),
    path('detach-file/<int:filewrapper_id>/', views.DetachFile.as_view(), name='detach-file'),
    path('post-file-download/<int:filewrapper_id>/', views.PostFileDownload.as_view(), name='post-file-download'),

    path('delete-post/<int:post_id>/', views.DeletePost.as_view(), name='delete-post'),
    path('delete-post/<int:post_id>/', views.DeletePost.as_view(), name='delete-post'),
    path('post-link/<int:post_id>/', views.PostLink.as_view(), name='post-link'),

    path('post-tag-information/(?P<tag_id>.+)/<int:post_id>/', views.PostTagInformation.as_view(), name='post-tag-information'),
    path('like-post/<int:post_id>/', views.LikePost.as_view(), name='like-post'),
    path('unlike-post/<int:post_id>/', views.UnlikePost.as_view(), name='unlike-post'),

    path('unbind-post-tags/<int:post_id>/', views.UnbindPostTags.as_view(), name='unbind-post-tags'),
    path('bind-post-tags/<int:post_id>/', views.BindPostTags.as_view(), name='bind-post-tags'),
    path('create-post-tagship/<int:post_id>/<int:tag_id>/', views.CreatePostTagship.as_view(), name='create-post-tagship'),
    path('delete-post-tagship/<int:post_id>/<int:tag_id>/', views.DeletePostTagship.as_view(), name='delete-post-tagship'),

    path('setup-post-filter/(?P<group_id>.+)', views.SetupPostFilter.as_view(), name='setup-post-filter'),
    path('find/', views.Find.as_view(), name='find'),

    path('cut-post/<int:post_id>/', views.CutPost.as_view(), name='cut-post'),
    path('copy-post/<int:post_id>/', views.CopyPost.as_view(), name='copy-post'),
    path('confirm-post-deletion/<int:post_id>/', views.ConfirmPostDeletion.as_view(), name='confirm-post-deletion'),
    path('select-fork-list/<int:post_id>/', views.SelectForkList.as_view(), name='select-fork-list'),
    path('create-post-fork/<int:ancestor_id>/<int:post_id>/', views.CreatePostFork.as_view(), name='create-post-fork'),
    path('pull-card-content/<int:ancestor_id>/<int:post_id>/', views.PullCardContent.as_view(), name='pull-card-content'),
    path('post-events/<int:post_id>/', views.PostEvents.as_view(), name='post-events'),
    path('pin-post/<int:post_id>/', views.PinPost.as_view(), name='pin-post'),
    path('unpin/<int:pin_id>/', views.Unpin.as_view(), name='unpin'),
    path('set-post-priority-down/<int:post0_id>/<int:post1_id>/', views.SetPostPriorityDown.as_view(), name='set-post-priority-down'),
    path('set-post-priority-up/<int:post0_id>/<int:post1_id>/', views.SetPostPriorityUp.as_view(), name='set-post-priority-up'),
    path('post-priority/<int:post_id>/', views.PostPriority.as_view(), name='post-priority'),
    path('restore-post/(?P<event_id>.+)/', views.RestorePost.as_view(), name='restore-post'),

]

comment_app/forms.py
from core_app.forms import FileAttachment
from sqlike.forms import SqLikeForm
from django import forms
from . import models

class CommentForm(forms.ModelForm):
    data = forms.CharField(strip=False, 
    required=False, widget=forms.Textarea)

    class Meta:
        model  = models.Comment
        exclude = ('post', 'owner')

class CommentFileWrapperForm(FileAttachment, forms.ModelForm):
    class Meta:
        model  = models.CommentFileWrapper
        fields = ('file', )

class CommentSearchForm(SqLikeForm, forms.ModelForm):
    class Meta:
        model  = models.CommentSearch
        exclude = ('user', 'organization')

comment_app/views.py
from django.views.generic import View
from django.shortcuts import render, redirect
from django.db.models import Q
from core_app.views import GuardianView, FileDownload, Event
from django.http import HttpResponse
from django.conf import settings
from post_app.models import Post
from comment_app.models import CommentSearch, EUpdateComment, ERestoreComment
from jscroll.wrappers import JScroll
import board_app.models
import core_app.models
from . import models
from . import forms

class Comment(GuardianView):
    def get(self, request, comment_id):
        comment = models.Comment.locate(self.me, self.me.default, comment_id)

        attachments = comment.commentfilewrapper_set.all()

        return render(request, 'comment_app/comment.html', 
        {'comment': comment, 'post': comment.post, 'attachments': attachments})

class CommentLink(GuardianView):
    def get(self, request, comment_id):
        comment = models.Comment.locate(self.me, self.me.default, comment_id)

        organizations = self.me.organizations.exclude(id=self.me.default.id)

        return render(request, 'comment_app/comment-link.html', 
        {'comment': comment, 'post': comment.post, 'user': self.me, 
        'organizations': organizations, 'default': self.me.default, 
        'organization': self.me.default, 'settings': settings})

class CreateComment(GuardianView):
    """
    """

    def get(self, request, post_id):
        # Make sure i have access to the post.
        post = Post.locate(self.me, self.me.default, post_id)
        form = forms.CommentForm()

        return render(request, 'comment_app/create-comment.html', 
        {'form':form, 'post': post})

    def post(self, request, post_id):
        post = Post.locate(self.me, self.me.default, post_id)
        form = forms.CommentForm(request.POST)

        if not form.is_valid():
            return render(request, 'comment_app/create-comment.html', 
                {'form': form, 'post':post,}, status=400)

        comment       = form.save(commit=False)
        comment.owner = self.me
        comment.post  = post
        comment.save()

        event = models.ECreateComment.objects.create(
        organization=self.me.default, child=post, user=self.me, comment=comment)
        event.dispatch(*post.ancestor.users.all())

        return redirect('post_app:refresh-post', post_id=post.id)

class AttachFile(GuardianView):
    """
    """

    def get(self, request, comment_id):
        comment = models.Comment.locate(self.me, self.me.default, comment_id)

        attachments = comment.commentfilewrapper_set.all()
        form = forms.CommentFileWrapperForm()

        return render(request, 'comment_app/attach-file.html', 
        {'comment':comment, 'form': form, 'attachments': attachments})

    def post(self, request, comment_id):
        comment = models.Comment.locate(self.me, self.me.default, comment_id)
        attachments = comment.commentfilewrapper_set.all()

        form = forms.CommentFileWrapperForm(request.POST, 
        request.FILES, user=self.me)

        if not form.is_valid():
            return render(request, 'comment_app/attach-file.html', 
                {'comment':comment, 'form': form, 'attachments': attachments})
        record = form.save(commit = False)
        record.organization = self.me.default
        record.comment = comment
        form.save()

        event = models.EAttachCommentFile.objects.create(
        organization=self.me.default, filewrapper=record, 
        comment=comment, user=self.me)

        event.dispatch(*comment.post.ancestor.users.all())
        event.save()

        return self.get(request, comment_id)

class DetachFile(GuardianView):
    """
    """

    def get(self, request, filewrapper_id):
        # Make sure i can access the post through the post group
        # or being a worker of the post.
        filewrapper = models.CommentFileWrapper.objects.filter(
        Q(comment__post__ancestor__users=self.me) | Q(comment__post__workers=self.me),
        comment__post__ancestor__organization=self.me.default, 
        id=filewrapper_id).distinct().first()

        attachments = filewrapper.comment.commentfilewrapper_set.all()

        form = forms.CommentFileWrapperForm()

        event = models.EDettachCommentFile.objects.create(
        organization=self.me.default, filename=filewrapper.file.name, 
        comment=filewrapper.comment, user=self.me)

        event.dispatch(*filewrapper.comment.post.ancestor.users.all())
        event.save()

        filewrapper.delete()

        return render(request, 'comment_app/attach-file.html', 
        {'comment':filewrapper.comment, 'form': form, 'attachments': attachments})

class UpdateComment(GuardianView):
    def get(self, request, comment_id):
        comment = models.Comment.locate(self.me, self.me.default, comment_id)
        return render(request, 'comment_app/update-comment.html',
        {'comment': comment, 'post': comment.post, 
        'form': forms.CommentForm(instance=comment),})

    def post(self, request, comment_id):
        record = models.Comment.locate(self.me, self.me.default, comment_id)
        event  = models.EUpdateComment.objects.create(comment_title=record.title,
        organization=self.me.default, child=record.post, comment_data=record.data,
        comment=record, user=self.me, comment_html=record.html)

        form = forms.CommentForm(request.POST, instance=record)

        if not form.is_valid():
            return render(request, 'comment_app/update-comment.html',
                {'form': form, 'post': comment.post, 
                    'comment':record, }, status=400)

        record.save()
        event.dispatch(*record.post.ancestor.users.all())
        event.save()

        return redirect('comment_app:comment', 
        comment_id=record.id)

class DeleteComment(GuardianView):
    def post(self, request, comment_id):
        comment = models.Comment.locate(self.me, self.me.default, comment_id)

        event = models.EDeleteComment.objects.create(organization=self.me.default,
        child=comment.post, comment=comment.title, user=self.me)

        event.dispatch(*comment.post.ancestor.users.all())
        comment.delete()

        return redirect('post_app:refresh-post', 
        post_id=comment.post.id)


class CommentFileDownload(FileDownload):
    def get(self, request, filewrapper_id):
        filewrapper = models.CommentFileWrapper.objects.filter(
        Q(comment__post__ancestor__users=self.me) | Q(comment__post__workers=self.me),
        comment__post__ancestor__organization=self.me.default, 
        id=filewrapper_id).distinct().first()

        return self.get_file_url(filewrapper.file)

class CommentDiff(GuardianView):
    def get(self, request, event_id):
        event = models.EUpdateComment.objects.get(id=event_id)
        comment = models.Comment.locate(self.me, self.me.default, event.comment.id)


        return render(request, 'comment_app/comment-diff.html', 
        {'comment': comment, 'event': event, 'post': comment.post})

class Find(GuardianView):
    def get(self, request):
        filter, _ = CommentSearch.objects.get_or_create(
        user=self.me, organization=self.me.default)

        form   = forms.CommentSearchForm(instance=filter)

        comments = models.Comment.objects.filter(
        Q(post__ancestor__users=self.me) &
        Q(post__ancestor__organization=self.me.default)).distinct()

        total  = comments.count()

        sqlike = models.Comment.from_sqlike()

        sqlike.feed(filter.pattern)

        comments = sqlike.run(comments)
        count = comments.count()

        comments = comments.only('post__label', 'post__id', 'data', 'id').order_by('id')
        elems = JScroll(self.me.id, 'comment_app/find-scroll.html', comments)

        return render(request, 'comment_app/find.html', 
        {'form': form, 'elems':  elems.as_div(), 'total': total, 'count': count})

    def post(self, request):
        filter, _ = CommentSearch.objects.get_or_create(
        user=self.me, organization=self.me.default)

        sqlike = models.Comment.from_sqlike()
        form  = forms.CommentSearchForm(request.POST, sqlike=sqlike, instance=filter)

        comments = models.Comment.objects.filter(
        Q(post__ancestor__users=self.me) &
        Q(post__ancestor__organization=self.me.default)).distinct()

        total = comments.count()

        if not form.is_valid():
            return render(request, 'comment_app/find.html', 
                {'form': form, 'total': total, 'count': 0}, status=400)
        form.save()

        comments = sqlike.run(comments)

        count =  comments.count()
        comments = comments.only('post__label', 'post__id', 'data', 'id').order_by('id')
        elems = JScroll(self.me.id, 'comment_app/find-scroll.html', comments)

        return render(request, 'comment_app/find.html', 
        {'form': form, 'elems':  elems.as_div(), 'total': total, 'count': count})

class RestoreComment(GuardianView):
    def post(self, request, event_id):
        event   = EUpdateComment.objects.get(id=event_id)
        comment = models.Comment.locate(self.me, self.me.default, event.comment.id)

        comment.title = event.comment_title
        comment.data  = event.comment_data
        comment.save()

        event = models.ERestoreComment.objects.create(
        event_html=event.html, organization=self.me.default, 
        post=comment.post, comment=comment, user=self.me)

        event.dispatch(*comment.post.ancestor.users.all())
        event.save()
        return redirect('comment_app:comment', comment_id=comment.id)

class CommentEvents(GuardianView):
    def get(self, request, comment_id):
        comment = models.Comment.locate(self.me, self.me.default, comment_id)

        query = Q(ecreatecomment__comment__id=comment.id) | \
        Q(eupdatecomment__comment__id=comment.id) |\
        Q(eattachcommentfile__comment__id=comment.id) |\

comment_app/templates/comment_app/attach-file.html
{% load bootstrap3 %}
{% load i18n %}
{% load bname %}

<script>
$('#CommentFileWrapperForm-{{comment.id}}').change(function(){
   var formData = new FormData($('#CommentFileWrapperForm-{{comment.id}}')[0]);
   $.ajax({
   url: '{% url 'comment_app:attach-file' comment.id  %}', 
   type: 'POST',
   success: function(data) {
   $('#comment-attachments-{{comment.id}}').html(data);},
   data: formData,
   cache: false,
   contentType: false,
   processData: false});
});

</script>


<form id="CommentFileWrapperForm-{{comment.id}}" enctype="multipart/form-data">
{% csrf_token %}
{% bootstrap_field form.file  size='md' %}
{% bootstrap_form_errors form type='non_fields' %}
</form>

{% for ind in attachments %}
<a class="e-get text-danger" data-shell="#comment-attachments-{{comment.id}}" href="#"
data-show="{% url 'comment_app:detach-file' ind.id %}"> 
<span class="glyphicon glyphicon-remove"></span></a> 
<a href="{% url 'comment_app:comment-file-download' ind.id %}" target="_blank"> {{ind.file.name|bname}} </a>

{% empty %}
No attachments.
{% endfor %}

comment_app/templates/comment_app/comment-diff.html
{% load bootstrap3 %}
{% load i18n %}

<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<span class="glyphicon glyphicon-file"></span> Change by 
<a href="#" data-toggle="popover" data-trigger="hover" title="{{event.user.email}}"  data-content="{{event.user.description}}"> {{event.user.name}} </a> 

</a>
on comment <a class="e-get"
data-shell="#bigModalContent"
data-show="{% url 'comment_app:comment' comment.id %}" 
href="{{event.comment.get_link_url}}"> 
<span class="glyphicon glyphicon-file"></span> {{comment.title|truncatechars:40}} </a>

from post <a class="e-get"
data-shell="#bigModalContent"
data-show="{% url 'post_app:post' post.id %}" 
href="{{event.post.get_link_url}}"> 
<span class="glyphicon glyphicon-file"></span> {{post.label|truncatechars:40}} </a>
</div>

<div class="modal-body">
<div class="panel panel-default">

<div class="panel-body">
<h4> {{event.comment_title | safe}} </h4>

{{event.comment_html | safe}}

<form id="restoreCommentForm"> {% csrf_token %} </form>

<a href="#" data-shell="#bigModalContent" data-form="#restoreCommentForm"  data-show="{% url 'comment_app:restore-comment' event.id  %}"
class="e-post"> <span class="glyphicon glyphicon-repeat"></span> Restore changes? </a>

</div>
</div>

<script>
$(function () {
    $('[data-toggle="popover"]').popover()
})
</script>

</div>

comment_app/templates/comment_app/comment-link.html
{% extends 'core_app/index.html' %}

{% load i18n %}
{% load static %}

{% block initializer %}
<script>
$(document).ready(function() {
    $('#main-view').load("{% url 'post_app:post' post.id %}");
    $('#bigModalContent').load("{% url 'comment_app:comment' comment.id %}");
    $('#bigModal').modal('show');

});

$(function () {
    $('[data-toggle="popover"]').popover()
})
</script>
{% endblock %}

comment_app/templates/comment_app/comment.html
{% load bootstrap3 %}
{% load i18n %}
{% load static %}

<div class="modal-header">
<form id="deleteCommentForm"> {% csrf_token %} </form>
<button type="button" class="close" data-dismiss="modal">&times;</button>
<span class="glyphicon glyphicon-book"></span> 
Comment by <a href="#" data-toggle="popover" data-trigger="hover" title="{{comment.owner.email}}"  data-content="{{comment.owner.description}}"> {{comment.owner.name}} </a>  on post
<a  href="{{post.get_link_url}}" data-shell="#main-view"  data-show="{% url 'post_app:post' post.id %}"
class="e-get"> <span class="glyphicon glyphicon-file"></span> {{post.label|truncatechars:60}} </a>

<a href="#" data-shell="#bigModalContent" data-show="{% url 'comment_app:find' %}"
class="e-get">  <span class="glyphicon glyphicon-search"></span> Comments </a>

</div>

<div class="modal-body">

{{comment.title}} 

{{comment.html | safe}}

<hr>
<div  style="font-size:80%">
<div id="comment-attachments-{{comment.id}}" style="min-height:52px;"> </div>

<script> 
$.get({ 
url: "{% url 'comment_app:attach-file' comment.id %}",
async: true},

function(data) {
    $('#comment-attachments-{{comment.id}}').html(data);
});

</script>

</div>


</div>

<div class="modal-footer">
<div class="pull-left">
<p> On <a href="{{comment.get_link_url}}" target="_blank"> {{comment.created}}</a> </p>
</div>

<div class="btn-group btn-group-sm">

<button  type="button" 
data-show="{% url 'comment_app:comment-events' comment.id %}"
data-shell="#mediumModalContent" 
class="btn btn-default e-get"> <span class="glyphicon glyphicon-bell"></span> {% trans "Activity" %} </button>

<button  type="button" 
data-show="{% url 'comment_app:update-comment' comment.id %}"
data-shell="#bigModalContent" 
class="btn btn-default e-get"> <span class="glyphicon glyphicon-edit"></span> {% trans "Update" %} </button>

<button  type="button" data-show="{% url 'comment_app:delete-comment' comment.id %}" data-form="#deleteCommentForm"
data-shell="#post-{{post.id}}" 
class="btn btn-default e-post"> <span class="glyphicon glyphicon-remove"></span> {% trans "Remove" %} </button>

<button  type="button" data-dismiss="modal" class="btn btn-default"> 
<span class="glyphicon glyphicon-thumbs-up"></span>     {% trans "Close" %}
</button>
</div>
</div>

<script>
$('#bigModal').one('hidden.bs.modal', function () {
    $('#post-{{post.id}}').load('{% url 'post_app:refresh-post' comment.post.id  %}');
})
$(function () {
    $('[data-toggle="popover"]').popover()
})

</script>

comment_app/templates/comment_app/create-comment.html
{% load bootstrap3 %}
{% load i18n %}

<form id="commentForm" enctype="multipart/form-data">

<div class="modal-body">
<button type="button" class="close" data-dismiss="modal">&times;</button>
{% bootstrap_field form.title  size='md' %}

{% csrf_token %}

<div class="collapse" id="data"> {% bootstrap_field form.data  size='md' %} </div>

{% bootstrap_form_errors form type='non_fields' %}

</div>
</form>


<div class="modal-footer">
<script>
$('#bigModal').one('hidden.bs.modal', function () {
    $('#post-{{post.id}}').load('{% url 'post_app:refresh-post' post.id  %}');
})

</script>

{% block buttons %}
<div class="btn-group btn-group-sm">

<button class="btn btn-default" type="button" data-toggle="collapse" data-target="#data">
<span class="glyphicon glyphicon-book"></span> Markdown</button> 

<button type="button" class="btn btn-default" data-dismiss="modal">
<span class="glyphicon glyphicon-thumbs-down"></span>
Cancel</button>

<button  type="button" data-form="#commentForm" 
data-shell="#post-{{post.id}}"  data-show="{% url 'comment_app:create-comment' post.id %}"
class="btn btn-default e-post"> 
<span class="glyphicon glyphicon-file"></span>     {% trans "Create" %}
</button>
</div>

{% endblock %}
</div>

comment_app/templates/comment_app/e-create-comment.html
{% extends 'group_app/event.html' %}
{% load i18n %}

{% block content %}
Comment <a class="e-get"
data-shell="#bigModalContent" 
data-show="{% url 'comment_app:comment' event.comment.id %}" href="{{event.comment.get_link_url}}"> 
<span class="glyphicon glyphicon-file"></span>
{{event.comment.title}} </a> was created on

<a class="e-get"
data-shell="#main-view"
data-show="{% url 'post_app:post' event.child.id %}" 
href="{{ event.child.get_link_url }}"> 
<span class="glyphicon glyphicon-file"></span>
{{event.child.label|truncatechars:40}} </a> 

{% endblock %}

comment_app/templates/comment_app/e-delete-comment.html
{% extends 'group_app/event.html' %}
{% load i18n %}

{% block content %}
Comment <span style="color:red">
<span class="glyphicon glyphicon-book"></span>
{{event.comment | truncatechars:30}}
</span> was deleted on

<a class="e-get"
data-shell="#main-view"
data-show="{% url 'post_app:post' event.child.id %}" 
href="{{event.child.get_link_url}}"> 
<span class="glyphicon glyphicon-file"></span>
{{event.child.label|truncatechars:40}} </a> 

{% endblock %}

comment_app/templates/comment_app/e-restore-comment.html
{% extends 'group_app/event.html' %}
{% load i18n %}

{% block content %}
Comment <a class="e-get" data-shell="#bigModalContent" data-show="{% url 'comment_app:comment' event.comment.id %}"  href="{{event.comment.get_link_url}}"> 
<span class="glyphicon glyphicon-book"></span> {{event.comment.title|truncatechars:50}} </a> 
was restored on post

<a class="e-get" data-shell="#main-view"
data-show="{% url 'post_app:post' event.post.id %}" href="{{event.post.get_link_url}}"> 
<span class="glyphicon glyphicon-file"></span>
{{event.post.label|truncatechars:50}} </a> ... from

<div class="panel panel-default">
<div class="panel-body">
{{event.event_html|safe}}
</div>
</div>

{% endblock %}

comment_app/templates/comment_app/e-update-comment.html
{% extends 'group_app/event.html' %}
{% load i18n %}

{% block content %}
Comment <a class="e-get"
data-shell="#bigModalContent" 
data-show="{% url 'comment_app:comment' event.comment.id %}" href="{{event.comment.get_link_url}}"> 
<span class="glyphicon glyphicon-file"></span>
{{event.comment.title}} </a> ...

<a class="e-get"
data-shell="#bigModalContent"
data-show="{% url 'comment_app:comment-diff' event.id %}" 
href="{{event.comment.get_link_url}}"> 
<span class="glyphicon glyphicon-check"></span> Diff </a>? was updated on post

<a class="e-get"
data-shell="#main-view"
data-show="{% url 'post_app:post' event.child.id %}" 
href="{{ event.child.get_link_url }}"> 
<span class="glyphicon glyphicon-file"></span>
{{event.child.label|truncatechars:40}} </a> 

{% endblock %}

comment_app/templates/comment_app/find.html
{% load bootstrap3 %}
{% load i18n %}


<div id="view-data">
<div class="modal-header">
<button type="button"  class="close" data-dismiss="modal">&times;</button>
<h4> 
<span class="glyphicon glyphicon-search"></span>

Comments
<span class="badge">{{count}}/{{total}}</span><h4>
</div>

<div class="modal-body">
<div class="pre-scrollable"> {{elems | safe}} </div>

<hr>

<form id="commentSearchForm" enctype="multipart/form-data">
{% csrf_token %}
{% bootstrap_field form.pattern  size='md'  %}

{% bootstrap_form_errors form type='non_fields' %}
</form>
</div>

</div>
</div>

<div class="modal-footer">
<button  type="button" data-form="#commentSearchForm"  data-show="{% url 'comment_app:find'  %}"
class="btn btn-default e-post"> {% trans "Filter" %} </button>

<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>

comment_app/templates/comment_app/update-commennt.html
{% extends "comment_app/create-comment.html" %}
{% load i18n %}
{% block title %}
<span class="glyphicon glyphicon-edit"></span> 
Update card
{% endblock %}

{% block buttons %}
<button  type="button" data-form="#commentForm" 
data-shell="#bigModalContent"  data-shell-error="#bigModalContent"  data-show="{% url 'comment_app:update-comment' comment.id %}"
class="btn btn-default e-post"> 
{% trans "Update" %}
</button>
{% endblock %}