arcamens/urls.py
from django.urls import path, include
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
    path(r'admin/', admin.site.urls),
     path(r'core_app/', include('core_app.urls')),
     path(r'group_app/', include('group_app.urls')),
     path(r'board_app/', include('board_app.urls')),
     path(r'feedback_app/', include('feedback_app.urls')),
     path(r'site_app/', include('site_app.urls')),
     path(r'cash_app/', include('cash_app.urls')),

     path(r'post_app/', include('post_app.urls', namespace='post_app')),
     path(r'paybills/', include('paybills.urls')),
     path(r'onesignal/', include('onesignal.urls')),
    path(r'card_app/', include('card_app.urls')),
    path(r'comment_app/', include('comment_app.urls')),
    path(r'note_app/', include('note_app.urls')),
    path(r'jscroll/', include('jscroll.urls')),

    path(r'bitbucket_app/', include('bitbucket_app.urls')),
    path(r'github_app/', include('github_app.urls')),

    path(r'list_app/', include('list_app.urls')),

    path(r'', RedirectView.as_view(pattern_name='site_app:index')),
]


# handler500 = 'core_app.views.default_error'

cash_app/urls.py
from django.conf.urls import re_path, include
from . import views

app_name = 'cash_app'
urlpatterns = [
    re_path('upgrade/', views.Upgrade.as_view(), name='upgrade'),
    re_path('paypal-manual-payment/', views.PaypalManualPayment.as_view(), name='paypal-manual-payment'),
    re_path('custom-payment/', views.CustomPayment.as_view(), name='custom-payment'),
    re_path('paypal-ipn/', views.PayPalIPN.as_view(), name='paypal-ipn'),
    re_path('custom-payment/', views.CustomPayment.as_view(), name='custom-payment'),
    re_path('confirm-downgrade-free/', views.ConfirmDowngradeFree.as_view(), name='confirm-downgrade-free'),
    re_path('downgrade-free/', views.DowngradeFree.as_view(), name='downgrade-free'),
    re_path('calculate-period-cost/', views.CalculatePeriodCost.as_view(), name='calculate-period-cost'),
]

core_app/urls.py
from django.views.generic.base import RedirectView
from django.conf.urls import re_path
from . import views

app_name = 'core_app'
urlpatterns = [
    re_path('index/', views.Index.as_view(), name='index'),
    re_path('set-timezone/', views.SetTimezone.as_view(), name='set-timezone'),
    re_path('disabled-account/(?P<user_id>.+)/', views.DisabledAccount.as_view(), name='disabled-account'),
    re_path('switch-organization/(?P<organization_id>.+)/', views.SwitchOrganization.as_view(), name='switch-organization'),
    re_path('update-user-information/', views.UpdateUserInformation.as_view(), name='update-user-information'),
    re_path('create-organization/', views.CreateOrganization.as_view(), name='create-organization'),
    re_path('select-organization/', views.SelectOrganization.as_view(), name='select-organization'),
    re_path('no-organization/', views.NoOrganization.as_view(), name='no-organization'),
    re_path('no-default/', views.NoDefault.as_view(), name='no-default'),

    re_path('seen-event/(?P<event_id>.+)/', views.SeenEvent.as_view(), name='seen-event'),
    re_path('setup-node-filter/', views.SetupNodeFilter.as_view(), name='setup-node-filter'),
    re_path('join-organization/(?P<organization_id>.+)/(?P<token>.+)/', views.JoinOrganization.as_view(), name='join-organization'),
    re_path('signup-from-invite/(?P<organization_id>.+)/(?P<token>.+)/', views.SignupFromInvite.as_view(), name='signup-from-invite'),
    re_path('update-organization/', views.UpdateOrganization.as_view(), name='update-organization'),
    re_path('delete-organization/', views.DeleteOrganization.as_view(), name='delete-organization'),
    re_path('list-users/', views.ListUsers.as_view(), name='list-users'),
    re_path('list-events/', views.ListEvents.as_view(), name='list-events'),
    re_path('shout/', views.Shout.as_view(), name='shout'),
    re_path('list-logs/', views.ListLogs.as_view(), name='list-logs'),
    re_path('all-seen/', views.AllSeen.as_view(), name='all-seen'),

    re_path('list-tags/', views.ListTags.as_view(), name='list-tags'),
    re_path('create-tag/', views.CreateTag.as_view(), name='create-tag'),
    re_path('delete-tag/(?P<tag_id>.+)/', views.DeleteTag.as_view(), name='delete-tag'),
    re_path('invite-organization-user/', views.InviteOrganizationUser.as_view(), name='invite-organization-user'),
    re_path('list-clipboard/', views.ListClipboard.as_view(), name='list-clipboard'),
    re_path('delete-all-clipboard/', views.DeleteAllClipboard.as_view(), name='delete-all-clipboard'),
    re_path('confirm-clipboard-deletion/', views.ConfirmClipboardDeletion.as_view(), name='confirm-clipboard-deletion'),
    re_path('update-password/', views.UpdatePassword.as_view(), name='update-password'),
    re_path('set-membership/(?P<organization_id>.+)/(?P<user_id>.+)/', views.SetMembership.as_view(), name='set-membership'),

    re_path('disabled-account/', views.DisabledAccount.as_view(), name='disabled-account'),
    re_path('remove-organization-user/(?P<user_id>.+)', views.RemoveOrganizationUser.as_view(), name='remove-organization-user'),
    re_path('cancel-invite/(?P<invite_id>.+)', views.CancelInvite.as_view(), name='cancel-invite'),
    re_path('list-invites/', views.ListInvites.as_view(), name='list-invites'),
    re_path('resend-invite/(?P<invite_id>.+)', views.ResendInvite.as_view(), name='resend-invite'),
    re_path('list-nodes/', views.ListNodes.as_view(), name='list-nodes'),
    re_path('list-public-organizations/', views.ListPublicOrganizations.as_view(), name='list-public-organizations'),
    re_path('resend-email-confirmation/', views.ResendEmailConfirmation.as_view(), name='resend-email-confirmation'),
    re_path('join-public-organization/(?P<organization_id>.+)/', views.JoinPublicOrganization.as_view(), name='join-public-organization'),
    re_path('not-public-organization/(?P<organization_id>.+)/', views.NotPublicOrganization.as_view(), name='not-public-organization'),
    re_path('join-from-link/(?P<organization_id>.+)/', views.JoinFromLink.as_view(), name='join-from-link'),

    re_path('unbind-user-tags/(?P<user_id>.+)/', views.UnbindUserTags.as_view(), name='unbind-user-tags'),
    re_path('bind-user-tags/(?P<user_id>.+)/', views.BindUserTags.as_view(), name='bind-user-tags'),
    re_path('create-user-tagship/(?P<user_id>.+)/(?P<tag_id>.+)/', views.CreateUserTagship.as_view(), name='create-user-tagship'),
    re_path('delete-user-tagship/(?P<user_id>.+)/(?P<tag_id>.+)/', views.DeleteUserTagship.as_view(), name='delete-user-tagship'),

]

site_app/urls.py
from django.conf.urls import re_path, include
from . import views

app_name = 'site_app'
urlpatterns = [
    re_path('index/', views.Index.as_view(), name='index'),
    re_path('logged-out/', views.LoggedOut.as_view(), name='logged-out'),
    re_path('help/', views.Help.as_view(), name='help'),
    re_path('login/', views.Login.as_view(), name='login'),
    re_path('logout/', views.Logout.as_view(), name='logout'),
    re_path('signup/', views.SignUp.as_view(), name='signup'),
    re_path('recover-account/', views.RecoverAccount.as_view(), name='recover-account'),
    re_path('redefine-password/(?P<user_id>.+)/(?P<token>.+)/', views.RedefinePassword.as_view(), name='redefine-password'),
    re_path('enable-account/(?P<user_id>.+)/(?P<token>.+)/', views.EnableAccount.as_view(), name='enable-account'),

]

site_app/models.py
from django.db import models
from django.db.models import Q
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse
from django.core.mail import send_mail
from django.conf import settings
import random

class RegisterProcessMixin:
    def save(self, *args, **kwargs):
        self.token = 'signup%s' % random.randint(1000, 10000)

        signup_url = reverse('site_app:enable-account', 
        kwargs={'user_id': self.user.id, 'token': self.token})

        self.signup_url = '%s%s' % (settings.LOCAL_ADDR, signup_url)

        send_mail('Confirm your account', '%s' % self.signup_url, 
        'noreply@arcamens.com', [self.user.email], fail_silently=False)
        super().save(*args, **kwargs)

class PasswordTicket(models.Model):
    token = models.CharField(null=True,
    blank=False, max_length=256)

    user = models.ForeignKey('core_app.User', null=False, on_delete=models.CASCADE,
    related_name='password_tickets')

    # expiration = models.DateTimeField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True, null=True)

class RegisterProcess(RegisterProcessMixin, models.Model):
    # email = models.EmailField(max_length=70, 
    # null=True, blank=False)
    user = models.OneToOneField('core_app.User', null=False, on_delete=models.CASCADE,
    related_name='register_process')

    # should have a count to avoid mail spam.
    token = models.CharField(null=True,
    blank=False, max_length=256)

    signup_url = models.CharField(null=True,
    blank=False, max_length=256)

    created = models.DateTimeField(auto_now_add=True, null=True)

site_app/forms.py
from slock.forms import SetPasswordForm
from captcha.fields import ReCaptchaField
from django import forms
import core_app.models

class RecoverAccountForm(forms.Form):
    email = forms.EmailField()

    def clean(self):
        super(RecoverAccountForm, self).clean()
        email = self.cleaned_data.get('email')

        try:
            user = core_app.models.User.objects.get(email = email)
        except Exception as e:
            raise forms.ValidationError("This user doesn't exist!")

class SignupForm(SetPasswordForm):
    captcha = ReCaptchaField()

    class Meta:
        model   = core_app.models.User
        exclude = ('organizations', 'default', 'enabled', 'tags',
        'c_storage', 'c_download','expiration', 'max_users', 'paid')

site_app/views.py
from paybills.submitters import ManualForm, SubscriptionForm
from django.db.models import Q
from core_app.models import Organization
from slock.views import LogoutView, LoginView
from slock.forms import SetPasswordForm
from django.shortcuts import render, redirect
from site_app.models import PasswordTicket, RegisterProcess
from django.core.mail import send_mail
from django.views.generic import View
from django.http import HttpResponse
from slock.forms import LoginForm
from django.urls import reverse
from django.conf import settings
from core_app.models import User
from cash_app.models import Period
from core_app.views import AuthenticatedView
import paybills.views
from . import forms
import group_app
import datetime
import time
import random

class Index(LoginView):
    def get(self, request):
        return render(request, 'site_app/index.html', 
        {'form':LoginForm()})

class LoggedOut(View):
    def get(self, request):
        return render(request, 'site_app/logged-out.html', {'settings': settings})

class Help(View):
    def get(self, request):
        return render(request, 'site_app/help.html')

class Login(LoginView):
    """
    """

    def get(self, request):
        return render(request, 'site_app/index.html', 
        {'form':LoginForm()})

    def post(self, request):
        form = LoginForm(request.session, request.POST)

        if not form.is_valid():
            return render(request, 'site_app/index.html',
                        {'form': form})

        form.authenticate()
        return redirect('core_app:index')

class Logout(LogoutView):
    """
    """

class SignUp(LoginView):
    """
    """

    def get(self, request):
        form = forms.SignupForm()
        return render(request, 'site_app/signup.html', 
        {'form': form, 'settings': settings})

    def post(self, request):
        """
        This is called after the user has filled the user fields
        and picked up a plan. The plan can be created on the fly
        or just be fixed(in case we decide futurely change how we
        charge on opus). 
        """
        form = forms.SignupForm(request.POST, request.FILES)
        if not form.is_valid():
            return render(request, 'site_app/signup.html', 
                {'form': form, 'settings': settings}, status=400)

        record = form.save()
        process = RegisterProcess.objects.create(user=record)

        # Authenticates the user afterwards so
        # he can resend email confirmation etc.
        request.session['user_id'] = record.id
        return render(request, 'site_app/confirm-email.html', {'user': record})

class EnableAccount(View):
    def get(self, request, user_id, token):
        query   = Q(user__id=user_id, token=token)
        process = None
        try:
            process = RegisterProcess.objects.get(query)
        except Exception as e:
            return render(request, 
                'site_app/invalid-confirmation-link.html', {})
        process.user.enabled = True
        process.user.save()
    
        # Create the free period record.
        period = Period.objects.create(paid=False, total=0, user=process.user)
        process.delete()

        request.session['user_id'] = user_id
        return redirect('core_app:index')

class RecoverAccount(LoginView):
    def get(self, request):
        form = forms.RecoverAccountForm()
        return render(request, 'site_app/recover-account.html', 
        {'form': form})

    def post(self, request):
        form = forms.RecoverAccountForm(request.POST)

        if not form.is_valid():
            return render(request, 
                'site_app/recover-account.html', {'form': form})

        email  = form.cleaned_data['email']
        user   = User.objects.get(email = email)
        token  = 'ticket%s%s' % (user.id, time.time())
        ticket = PasswordTicket.objects.create(token=token, user=user)
        url    = reverse('site_app:redefine-password', kwargs={
        'user_id': user.id, 'token': token})

        url = '%s%s' % (settings.LOCAL_ADDR, url)

        send_mail('Account recover %s' % user.name,
        '%s' % url, 'noreply@arcamens.com', [email],
        fail_silently=False)

        return render(request, 'site_app/recover-mail-sent.html', 
        {'form': form, 'user': user})

class RedefinePassword(LoginView):
    def get(self, request, user_id, token):
        user = User.objects.get(id = user_id)
        form = SetPasswordForm()

        return render(request, 'site_app/redefine-password.html', 
        {'user': user, 'form': form, 'token': token})

    def post(self, request, user_id, token):
        # First attempt to grab the ticket
        # if it doesnt then it just throws an inter server error.
        user   = User.objects.get(id = user_id)
        ticket = PasswordTicket.objects.filter(user=user)
        form   = SetPasswordForm(request.POST, instance=user)

        # The logic to check if password matches should be handled
        # in the RedefinePasswordForm.
        if not form.is_valid():
            return render(request, 'site_app/redefine-password.html',
                 {'form': form, 'user': user, 'token': token})

        # Delete all password redefinition tickets.
        ticket.delete()

        form.save()
        # Redefine the password.
        # user.password = form.cleaned_data['password']
        # user.save()

        # Log the user.
        request.session['user_id'] = user.id

        # Redirect to the application.
        return redirect('core_app:index')

site_app/templates/site_app/confirm-downgrade-free.html
{% load bootstrap3 %}
{% load i18n %}

<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h4> <span class="glyphicon glyphicon-heart-empty"></span> Free Plan </h4>
</div>

<div class="modal-body">

<p class="text-warning">
Are you sure you want to downgrade?
</p>

<p> <b> Total Users:  {{n_users}} </b>
<br>
<small class="text-info">  All your organization users summed up. </small>
</p>

<p> 
<b> Max Users: {{me.max_users}} </b>
</br>
<small class="text-info"> The max amount of users all your organizations can have when summed up. </small></p>

</div>

<div class="modal-footer">
<button  type="button" data-show="{% url 'site_app:upgrade' %}"
class="btn btn-default e-get"> {% trans "Back" %} </button>

<button  type="button" data-show="{% url 'site_app:downgrade-free' %}" 
class="btn btn-default e-get"> {% trans "Do it!" %} </button>

</div>

site_app/templates/site_app/confirm-email.html
{% load bootstrap3 %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
<title>Arcamens</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.js" type="text/javascript"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>

<div class="container">
  <div class="jumbotron">
    <h1>Arcamens</h1> 

<p>An e-mail was sent to {{user.email}}. Click on the link for confirming your account. </p> 

<a href="{% url 'core_app:resend-email-confirmation' %}"> Resend E-mail? </a>

<a href="{% url 'site_app:logout' %}"> Logout? </a> 

</div>
</div>


</body>
</html>

site_app/templates/site_app/custom-payment.html
{% load bootstrap3 %}
{% load i18n %}

<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h4> <span class="glyphicon glyphicon-credit-card"></span> Payment Settings </h4>

</div>
<div class="modal-body">
<p class="text-info"> 
Send an E-mail to admins@arcamens.com with your Account's details. 
</p>

<p class="text-warning"> 
Inform your necessities regarding max users and period of time.
</p>

</div>

<div class="modal-footer">
<button  type="button" data-show="{% url 'site_app:upgrade' %}" 
class="btn btn-default e-get"> {% trans "Back" %} </button>
</div>

site_app/templates/site_app/index.html
<!DOCTYPE html>
{% load bootstrap3 %}
{% load i18n %}
{% load static %}

<html lang="en">
<head>
<meta charset="utf-8" />
<title>Arcamens</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="/static/jquery-ui.js"> </script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<script src="/static/input-extensions.js"> </script>

<link rel="apple-touch-icon" sizes="180x180" href="/static/icons/apple-touch-icon.png">
<link rel="icon" type="image/png" href="/static/icons/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/static/icons/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/static/icons/manifest.json">
<link rel="mask-icon" href="/static/icons/safari-pinned-tab.svg" color="#5bbad5">
<link rel="shortcut icon" href="/static/icons/favicon.ico">
<meta name="apple-mobile-web-app-title" content="Arcamens">
<meta name="application-name" content="arcamens">
<meta name="msapplication-config" content="/static/icons/browserconfig.xml">
<meta name="theme-color" content="#ffffff">

<style>
footer{
   background-color: #424558;
    bottom: 0;
    left: 0;
    right: 0;
    text-align: center;
    color: #CCC;
}

footer p {
    padding: 10.5px;
    margin: 0px;
    line-height: 100%;
}
</style>

</head>
<body>


<nav class="navbar navbar-inverse" style="background-color:#071152">
<div class="container-fluid">
<div class="navbar-header">
<a class="navbar-brand" href="#">Arcamens </a>
    
</div>

<ul class="nav navbar-nav">
<li><a href="{% url 'site_app:signup' %}" >
<span class="glyphicon glyphicon-user"></span> {% trans "Sign up" %}</a></li>

<li><a href="{% static 'site_app/help/index.html' %}" target="_blank">
<span class="glyphicon glyphicon-book"></span> {% trans "Help" %}</a></li>

</ul>

<ul class="nav navbar-right">

<form class="navbar-form navbar-left" method="post" action="{% url 'site_app:login' %}">
{% csrf_token %}

{% bootstrap_field form.email layout='inline' %}
{% bootstrap_field form.password layout='inline' %}
{% buttons submit='Sign in' layout='inline' %}{% endbuttons %}

</form>

</ul>

</div>
</nav>

<div class="container">
{% if form.errors %}
<div class="text-right">
<a href="{% url 'site_app:recover-account' %}" >
<span class="glyphicon glyphicon-lock"></span> Lost password?</a>
</div>
{% endif %}

{% bootstrap_form_errors form type='non_fields' %}
</div>

{% include 'site_app/home.html' %}
</div>

<footer style="align-center">
<p>© 2018<a style="color:#0a93a6; text-decoration:none;" href="#"> Arcamens</a>, All rights reserved 2017-2018.
<br> 
<a href="mailto:contact@arcamens.com">contact@arcamens.com</a>
</p>
</footer>

</body>
</html>

site_app/templates/site_app/invalid-confirmation-link.html
{% load bootstrap3 %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
<title>Arcamens</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.js" type="text/javascript"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>

<div class="container">
  <div class="jumbotron">
    <h1>Arcamens</h1> 

<p>This account confirmation link is no longer active.</p> 

<a href="{% url 'site_app:index' %}"> Login? </a> 

</div>
</div>


</body>
</html>

site_app/templates/site_app/paypal-manual-payment.html
{% load bootstrap3 %}
{% load i18n %}

<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h3> <span class="glyphicon glyphicon-credit-card"></span>

Paypal <small> Manual Payment </small></h3>

</div>
<div class="modal-body">

<form id="paypalManualPaymentForm" enctype="multipart/form-data">
{% csrf_token %}

{% bootstrap_field form.max_users  size='md' %}
{% bootstrap_field form.expiration  size='md' %}

{% bootstrap_form_errors form type='non_fields' %}

</form>
<p> <b> Total Cost: {{cost}} {{settings.USER_COST}}</b> <br>
<small class="text-info"> Cost based on current expiration and max users limit. 

<span class="text-warning"> Cost per user {{settings.USER_COST}} {{settings.USER_COST}} per 30 days. </span>
</small></p>

</div>

<div class="modal-footer">

<button  type="button" data-show="{% url 'site_app:upgrade' %}" 
class="btn btn-default e-get"> {% trans "Back" %} </button>

<button  type="button" data-show="{% url 'site_app:calculate-period-cost' %}" data-form="#paypalManualPaymentForm"
class="btn btn-default e-post"> {% trans "Calc/Cost" %} </button>

<button  type="button" data-show="{% url 'site_app:paypal-manual-payment' %}" data-form="#paypalManualPaymentForm"
class="btn btn-default e-post"> {% trans "Purchase" %} </button>

</div>

site_app/templates/site_app/recover-account.html
{% load bootstrap3 %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
<title>Arcamens</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.js" type="text/javascript"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>

<div class="container">
  <div class="jumbotron">
    <h1>Arcamens</h1> 

<p>Insert your primary or secondary e-mail. We'll send you a link for
redefining a new password. </p> 

<div class="row">
<div class="col-md-5">
<form action="{% url 'site_app:recover-account' %}" method="post">
{% csrf_token %}
{% bootstrap_field form.email  size='md' %}
{% buttons submit='Send' layout='inline' %}{% endbuttons %}

</form>
</div>

</div>

</div>
{% bootstrap_form_errors form type='non_fields' %}

</div>


</body>
</html>

site_app/templates/site_app/recover-mail-sent.html
{% load bootstrap3 %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
<title>Arcamens</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.js" type="text/javascript"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>

<div class="container">
  <div class="jumbotron">
    <h1>Arcamens</h1> 

<p>An e-mail was sent to {{user.email}}. 
Click on the link to reset your password.</p> 

<a href="{% url 'site_app:login' %}"> Login? </a> 

</div>
</div>


</body>
</html>

site_app/templates/site_app/upgrade.html
{% load bootstrap3 %}
{% load i18n %}

<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h4> <span class="glyphicon glyphicon-credit-card"></span> Payment Settings </h4>

</div>
<div class="modal-body">
<p class="text-info"> Your account can have at most {{ me.max_users }} users.
</p>

<p class="text-warning">
It will expire on {{ me.expiration }}.<br>
</p>

<h5 class="text-info"> Your purchases: </h5>
<div class="pre-scrollable" style="font-size:90%">
{% for ind in items %}
<p> 
Max Users: {{ind.period.max_users}} 
<br>
Total: {{ind.period.total}} {{CURRENCY_CODE}}
<br>
Expiration: {{ind.period.expiration}}
<br>
Type: {% if ind.period.paid %} Plan Paid {% else %}  Plan Free {% endif %}
<br>
Date: {{ind.period.created}}
<br>

{% if ind.payment_process.success %}
<small class="text-success"> Paid successfully! </small>
{% endif %}
<p>
{% empty %}
<p> No items. </p>
{% endfor %}

</div>

</div>

<div class="modal-footer">

<div class="text-center">
 <a class="e-get" data-show="{% url 'site_app:paypal-manual-payment' %}" href="#"> Paypal </a> 
<a class="e-get" data-show="{% url 'site_app:custom-payment' %}" href="#"> Custom </a> 

{% if me.paid %}
<a class="e-get" data-show="{% url 'site_app:confirm-downgrade-free' %}" href="#"> Downgrade Free </a> 
{% endif %}
</div>

</div>